//! Bulk operations for Attendance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAttendanceDto;
use crate::application::service::AttendanceService;
use crate::domain::entity::Attendance;

/// Bulk operation handler for Attendance entities.
///
/// Wraps `AttendanceService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AttendanceBulkService = GenericBulkService<Attendance, CreateAttendanceDto, AttendanceService>;

// <<< CUSTOM
// END CUSTOM
