//! Bulk operations for Employee entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateEmployeeDto;
use crate::application::service::EmployeeService;
use crate::domain::entity::Employee;

/// Bulk operation handler for Employee entities.
///
/// Wraps `EmployeeService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type EmployeeBulkService = GenericBulkService<Employee, CreateEmployeeDto, EmployeeService>;

// <<< CUSTOM
// END CUSTOM
