//! Bulk operations for LeaveBalance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateLeaveBalanceDto;
use crate::application::service::LeaveBalanceService;
use crate::domain::entity::LeaveBalance;

/// Bulk operation handler for LeaveBalance entities.
///
/// Wraps `LeaveBalanceService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type LeaveBalanceBulkService = GenericBulkService<LeaveBalance, CreateLeaveBalanceDto, LeaveBalanceService>;

// <<< CUSTOM
// END CUSTOM
