//! Bulk operations for LeaveType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateLeaveTypeDto;
use crate::application::service::LeaveTypeService;
use crate::domain::entity::LeaveType;

/// Bulk operation handler for LeaveType entities.
///
/// Wraps `LeaveTypeService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type LeaveTypeBulkService = GenericBulkService<LeaveType, CreateLeaveTypeDto, LeaveTypeService>;

// <<< CUSTOM
// END CUSTOM
