//! Bulk operations for LeaveApplication entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateLeaveApplicationDto;
use crate::application::service::LeaveApplicationService;
use crate::domain::entity::LeaveApplication;

/// Bulk operation handler for LeaveApplication entities.
///
/// Wraps `LeaveApplicationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type LeaveApplicationBulkService = GenericBulkService<LeaveApplication, CreateLeaveApplicationDto, LeaveApplicationService>;

// <<< CUSTOM
// END CUSTOM
