//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod attendance_bulk;
pub mod employee_bulk;
pub mod leave_application_bulk;
pub mod leave_balance_bulk;
pub mod leave_type_bulk;

pub use attendance_bulk::AttendanceBulkService;
pub use employee_bulk::EmployeeBulkService;
pub use leave_application_bulk::LeaveApplicationBulkService;
pub use leave_balance_bulk::LeaveBalanceBulkService;
pub use leave_type_bulk::LeaveTypeBulkService;

// <<< CUSTOM
// END CUSTOM
