//! Employee DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Employee;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EmployeeStatus;
use crate::domain::entity::EmploymentType;
use crate::domain::entity::TaxStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Employee
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEmployeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "employee_number")]
    pub employee_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "first_name")]
    pub first_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub designation: Option<String>,
    #[serde(alias = "employment_type")]
    pub employment_type: EmploymentType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "date_of_joining")]
    pub date_of_joining: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "date_of_exit")]
    pub date_of_exit: Option<DateTime<Utc>>,
    pub status: EmployeeStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nik: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[serde(alias = "tax_status")]
    pub tax_status: TaxStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bank_account_no")]
    pub bank_account_no: Option<String>,
    #[serde(alias = "base_salary")]
    pub base_salary: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Employee
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEmployeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "employee_number")]
    pub employee_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "first_name")]
    pub first_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub designation: Option<String>,
    #[serde(alias = "employment_type")]
    pub employment_type: EmploymentType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "date_of_joining")]
    pub date_of_joining: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "date_of_exit")]
    pub date_of_exit: Option<DateTime<Utc>>,
    pub status: EmployeeStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nik: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[serde(alias = "tax_status")]
    pub tax_status: TaxStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "bank_account_no")]
    pub bank_account_no: Option<String>,
    #[serde(alias = "base_salary")]
    pub base_salary: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Employee
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEmployeeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_number")]
    pub employee_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "first_name")]
    pub first_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub designation: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "employment_type")]
    pub employment_type: Option<EmploymentType>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_of_joining")]
    pub date_of_joining: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_of_exit")]
    pub date_of_exit: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<EmployeeStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 16)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nik: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_status")]
    pub tax_status: Option<TaxStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "bank_account_no")]
    pub bank_account_no: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "base_salary")]
    pub base_salary: Option<Decimal>,
}

impl PatchEmployeeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_number.is_some() || self.user_id.is_some() || self.department_id.is_some() || self.first_name.is_some() || self.last_name.is_some() || self.designation.is_some() || self.employment_type.is_some() || self.date_of_joining.is_some() || self.date_of_exit.is_some() || self.status.is_some() || self.nik.is_some() || self.npwp.is_some() || self.tax_status.is_some() || self.bank_account_no.is_some() || self.base_salary.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Employee entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub employee_number: String,
    pub user_id: Option<Uuid>,
    pub department_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub first_name: String,
    pub last_name: Option<String>,
    pub designation: Option<String>,
    pub employment_type: EmploymentType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub date_of_joining: DateTime<Utc>,
    pub date_of_exit: Option<DateTime<Utc>>,
    pub status: EmployeeStatus,
    pub nik: Option<String>,
    pub npwp: Option<String>,
    pub tax_status: TaxStatus,
    pub bank_account_no: Option<String>,
    pub base_salary: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Employee entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeListResponseDto {
    /// List of items
    pub items: Vec<EmployeeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EmployeeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EmployeeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_number: String,
    pub user_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Employee> for EmployeeResponseDto {
    fn from(entity: Employee) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_number: entity.employee_number,
            user_id: entity.user_id,
            department_id: entity.department_id,
            first_name: entity.first_name,
            last_name: entity.last_name,
            designation: entity.designation,
            employment_type: entity.employment_type,
            date_of_joining: entity.date_of_joining,
            date_of_exit: entity.date_of_exit,
            status: entity.status,
            nik: entity.nik,
            npwp: entity.npwp,
            tax_status: entity.tax_status,
            bank_account_no: entity.bank_account_no,
            base_salary: entity.base_salary,
            metadata: entity.metadata,
        }
    }
}

impl From<Employee> for EmployeeSummaryDto {
    fn from(entity: Employee) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_number: entity.employee_number,
            user_id: entity.user_id,
            created_at,
        }
    }
}

impl From<CreateEmployeeDto> for Employee {
    fn from(dto: CreateEmployeeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_number: dto.employee_number,
            user_id: dto.user_id,
            department_id: dto.department_id,
            first_name: dto.first_name,
            last_name: dto.last_name,
            designation: dto.designation,
            employment_type: dto.employment_type,
            date_of_joining: dto.date_of_joining,
            date_of_exit: dto.date_of_exit,
            status: dto.status,
            nik: dto.nik,
            npwp: dto.npwp,
            tax_status: dto.tax_status,
            bank_account_no: dto.bank_account_no,
            base_salary: dto.base_salary,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Employee> for EmployeeResponseDto {
    fn from(entity: &Employee) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_number: entity.employee_number.clone(),
            user_id: entity.user_id.clone(),
            department_id: entity.department_id.clone(),
            first_name: entity.first_name.clone(),
            last_name: entity.last_name.clone(),
            designation: entity.designation.clone(),
            employment_type: entity.employment_type.clone(),
            date_of_joining: entity.date_of_joining.clone(),
            date_of_exit: entity.date_of_exit.clone(),
            status: entity.status.clone(),
            nik: entity.nik.clone(),
            npwp: entity.npwp.clone(),
            tax_status: entity.tax_status.clone(),
            bank_account_no: entity.bank_account_no.clone(),
            base_salary: entity.base_salary.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEmployeeDto> for Employee {
    fn from_create_dto(dto: CreateEmployeeDto) -> backbone_core::ServiceResult<Self> {
        Ok(Employee::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEmployeeDto> for Employee {
    fn apply_update(mut self, dto: UpdateEmployeeDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_number = dto.employee_number;
        self.user_id = dto.user_id;
        self.department_id = dto.department_id;
        self.first_name = dto.first_name;
        self.last_name = dto.last_name;
        self.designation = dto.designation;
        self.employment_type = dto.employment_type;
        self.date_of_joining = dto.date_of_joining;
        self.date_of_exit = dto.date_of_exit;
        self.status = dto.status;
        self.nik = dto.nik;
        self.npwp = dto.npwp;
        self.tax_status = dto.tax_status;
        self.bank_account_no = dto.bank_account_no;
        self.base_salary = dto.base_salary;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Employee here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
