//! LeaveApplication DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::LeaveApplication;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::LeaveStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new LeaveApplication
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateLeaveApplicationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "leave_type_id")]
    pub leave_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "from_date")]
    pub from_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "to_date")]
    pub to_date: DateTime<Utc>,
    pub days: Decimal,
    pub status: LeaveStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approved_by")]
    pub approved_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approved_at")]
    pub approved_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a LeaveApplication
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateLeaveApplicationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "leave_type_id")]
    pub leave_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "from_date")]
    pub from_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "to_date")]
    pub to_date: DateTime<Utc>,
    pub days: Decimal,
    pub status: LeaveStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approved_by")]
    pub approved_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approved_at")]
    pub approved_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a LeaveApplication
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchLeaveApplicationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "leave_type_id")]
    pub leave_type_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "from_date")]
    pub from_date: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "to_date")]
    pub to_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub days: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<LeaveStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approved_by")]
    pub approved_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approved_at")]
    pub approved_at: Option<DateTime<Utc>>,
}

impl PatchLeaveApplicationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.leave_type_id.is_some() || self.from_date.is_some() || self.to_date.is_some() || self.days.is_some() || self.status.is_some() || self.reason.is_some() || self.approved_by.is_some() || self.approved_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for LeaveApplication entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeaveApplicationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub leave_type_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub from_date: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub to_date: DateTime<Utc>,
    pub days: Decimal,
    pub status: LeaveStatus,
    pub reason: Option<String>,
    pub approved_by: Option<Uuid>,
    pub approved_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for LeaveApplication entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeaveApplicationListResponseDto {
    /// List of items
    pub items: Vec<LeaveApplicationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl LeaveApplicationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<LeaveApplicationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeaveApplicationSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub leave_type_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<LeaveApplication> for LeaveApplicationResponseDto {
    fn from(entity: LeaveApplication) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            leave_type_id: entity.leave_type_id,
            from_date: entity.from_date,
            to_date: entity.to_date,
            days: entity.days,
            status: entity.status,
            reason: entity.reason,
            approved_by: entity.approved_by,
            approved_at: entity.approved_at,
            metadata: entity.metadata,
        }
    }
}

impl From<LeaveApplication> for LeaveApplicationSummaryDto {
    fn from(entity: LeaveApplication) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            leave_type_id: entity.leave_type_id,
            created_at,
        }
    }
}

impl From<CreateLeaveApplicationDto> for LeaveApplication {
    fn from(dto: CreateLeaveApplicationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            leave_type_id: dto.leave_type_id,
            from_date: dto.from_date,
            to_date: dto.to_date,
            days: dto.days,
            status: dto.status,
            reason: dto.reason,
            approved_by: dto.approved_by,
            approved_at: dto.approved_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&LeaveApplication> for LeaveApplicationResponseDto {
    fn from(entity: &LeaveApplication) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            leave_type_id: entity.leave_type_id.clone(),
            from_date: entity.from_date.clone(),
            to_date: entity.to_date.clone(),
            days: entity.days.clone(),
            status: entity.status.clone(),
            reason: entity.reason.clone(),
            approved_by: entity.approved_by.clone(),
            approved_at: entity.approved_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateLeaveApplicationDto> for LeaveApplication {
    fn from_create_dto(dto: CreateLeaveApplicationDto) -> backbone_core::ServiceResult<Self> {
        Ok(LeaveApplication::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateLeaveApplicationDto> for LeaveApplication {
    fn apply_update(mut self, dto: UpdateLeaveApplicationDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.leave_type_id = dto.leave_type_id;
        self.from_date = dto.from_date;
        self.to_date = dto.to_date;
        self.days = dto.days;
        self.status = dto.status;
        self.reason = dto.reason;
        self.approved_by = dto.approved_by;
        self.approved_at = dto.approved_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to LeaveApplication here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

