//! LeaveType DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::LeaveType;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new LeaveType
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateLeaveTypeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_paid")]
    pub is_paid: bool,
    #[serde(alias = "annual_quota_days")]
    pub annual_quota_days: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "allow_carry_forward")]
    pub allow_carry_forward: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a LeaveType
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateLeaveTypeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_paid")]
    pub is_paid: bool,
    #[serde(alias = "annual_quota_days")]
    pub annual_quota_days: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "allow_carry_forward")]
    pub allow_carry_forward: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a LeaveType
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchLeaveTypeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_paid")]
    pub is_paid: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "annual_quota_days")]
    pub annual_quota_days: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "allow_carry_forward")]
    pub allow_carry_forward: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchLeaveTypeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.is_paid.is_some() || self.annual_quota_days.is_some() || self.allow_carry_forward.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for LeaveType entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeaveTypeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_paid: bool,
    pub annual_quota_days: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub allow_carry_forward: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for LeaveType entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeaveTypeListResponseDto {
    /// List of items
    pub items: Vec<LeaveTypeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl LeaveTypeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<LeaveTypeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeaveTypeSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: String,
    pub is_paid: bool,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<LeaveType> for LeaveTypeResponseDto {
    fn from(entity: LeaveType) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            is_paid: entity.is_paid,
            annual_quota_days: entity.annual_quota_days,
            allow_carry_forward: entity.allow_carry_forward,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<LeaveType> for LeaveTypeSummaryDto {
    fn from(entity: LeaveType) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            is_paid: entity.is_paid,
            created_at,
        }
    }
}

impl From<CreateLeaveTypeDto> for LeaveType {
    fn from(dto: CreateLeaveTypeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            name: dto.name,
            is_paid: dto.is_paid,
            annual_quota_days: dto.annual_quota_days,
            allow_carry_forward: dto.allow_carry_forward,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&LeaveType> for LeaveTypeResponseDto {
    fn from(entity: &LeaveType) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            name: entity.name.clone(),
            is_paid: entity.is_paid.clone(),
            annual_quota_days: entity.annual_quota_days.clone(),
            allow_carry_forward: entity.allow_carry_forward.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateLeaveTypeDto> for LeaveType {
    fn from_create_dto(dto: CreateLeaveTypeDto) -> backbone_core::ServiceResult<Self> {
        Ok(LeaveType::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateLeaveTypeDto> for LeaveType {
    fn apply_update(mut self, dto: UpdateLeaveTypeDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.name = dto.name;
        self.is_paid = dto.is_paid;
        self.annual_quota_days = dto.annual_quota_days;
        self.allow_carry_forward = dto.allow_carry_forward;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to LeaveType here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
