//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod attendance_specification;
pub mod employee_specification;
pub mod leave_application_specification;
pub mod leave_balance_specification;
pub mod leave_type_specification;

// <<< CUSTOM
// END CUSTOM
