//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attendance_domain_policy;
pub mod employee_domain_policy;
pub mod leave_application_domain_policy;
pub mod leave_balance_domain_policy;
pub mod leave_type_domain_policy;

pub use attendance_domain_policy::AttendanceDomainPolicy;
pub use employee_domain_policy::EmployeeDomainPolicy;
pub use leave_application_domain_policy::LeaveApplicationDomainPolicy;
pub use leave_balance_domain_policy::LeaveBalanceDomainPolicy;
pub use leave_type_domain_policy::LeaveTypeDomainPolicy;

// <<< CUSTOM
// END CUSTOM
