//! Application service for Attendance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `attendance_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAttendanceDto, UpdateAttendanceDto};
use crate::domain::entity::Attendance;
use crate::infrastructure::persistence::AttendanceRepository;

/// Application service for Attendance entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `attendance_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AttendanceServiceCustom {
///     inner: Arc<AttendanceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AttendanceService = GenericCrudService<
    Attendance,
    CreateAttendanceDto,
    UpdateAttendanceDto,
    AttendanceRepository,
>;

// <<< CUSTOM
// END CUSTOM
