//! Application service for Employee entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `employee_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEmployeeDto, UpdateEmployeeDto};
use crate::domain::entity::Employee;
use crate::infrastructure::persistence::EmployeeRepository;

/// Application service for Employee entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `employee_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EmployeeServiceCustom {
///     inner: Arc<EmployeeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EmployeeService = GenericCrudService<
    Employee,
    CreateEmployeeDto,
    UpdateEmployeeDto,
    EmployeeRepository,
>;

// <<< CUSTOM
// END CUSTOM
