//! Application service for LeaveType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `leave_type_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLeaveTypeDto, UpdateLeaveTypeDto};
use crate::domain::entity::LeaveType;
use crate::infrastructure::persistence::LeaveTypeRepository;

/// Application service for LeaveType entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `leave_type_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LeaveTypeServiceCustom {
///     inner: Arc<LeaveTypeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LeaveTypeService = GenericCrudService<
    LeaveType,
    CreateLeaveTypeDto,
    UpdateLeaveTypeDto,
    LeaveTypeRepository,
>;

// <<< CUSTOM
// END CUSTOM
