//! Application service for LeaveApplication entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `leave_application_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLeaveApplicationDto, UpdateLeaveApplicationDto};
use crate::domain::entity::LeaveApplication;
use crate::infrastructure::persistence::LeaveApplicationRepository;

/// Application service for LeaveApplication entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `leave_application_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LeaveApplicationServiceCustom {
///     inner: Arc<LeaveApplicationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LeaveApplicationService = GenericCrudService<
    LeaveApplication,
    CreateLeaveApplicationDto,
    UpdateLeaveApplicationDto,
    LeaveApplicationRepository,
>;

// <<< CUSTOM
// END CUSTOM
