//! Application service for LeaveBalance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `leave_balance_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLeaveBalanceDto, UpdateLeaveBalanceDto};
use crate::domain::entity::LeaveBalance;
use crate::infrastructure::persistence::LeaveBalanceRepository;

/// Application service for LeaveBalance entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `leave_balance_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LeaveBalanceServiceCustom {
///     inner: Arc<LeaveBalanceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LeaveBalanceService = GenericCrudService<
    LeaveBalance,
    CreateLeaveBalanceDto,
    UpdateLeaveBalanceDto,
    LeaveBalanceRepository,
>;

// <<< CUSTOM
// END CUSTOM
