//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod attendance_service;
pub mod employee_service;
pub mod leave_application_service;
pub mod leave_balance_service;
pub mod leave_type_service;

// <<< CUSTOM
pub mod hr_events;
pub mod hr_ports;
pub mod hr_write_service;
// END CUSTOM

pub use attendance_service::AttendanceService;
pub use employee_service::EmployeeService;
pub use leave_application_service::LeaveApplicationService;
pub use leave_balance_service::LeaveBalanceService;
pub use leave_type_service::LeaveTypeService;
// <<< CUSTOM
pub use hr_events::{
    EmployeeExited, EmployeeOnboarded, HrEvent, HrEventSink, LeaveApproved, LoggingSink,
};
pub use hr_ports::{DepartmentRef, OrgPort, HrRejected};
pub use hr_write_service::{
    HrError, HrWriteService, NewAttendance, NewEmployee, NewLeaveApplication, NewLeaveType,
    PeriodSummary,
};
// END CUSTOM