-- Employee Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the hr.employees table.
-- Customize this file to add your initial data.

-- INSERT INTO hr.employees (
--     id,
--     company_id,
--     employee_number,
--     user_id,
--     department_id,
--     first_name,
--     last_name,
--     designation,
--     employment_type,
--     date_of_joining,
--     date_of_exit,
--     status,
--     nik,
--     npwp,
--     tax_status,
--     bank_account_no,
--     base_salary,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO hr.employees (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

