-- LeaveApplication Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the hr.leave_applications table.
-- Customize this file to add your initial data.

-- INSERT INTO hr.leave_applications (
--     id,
--     company_id,
--     employee_id,
--     leave_type_id,
--     from_date,
--     to_date,
--     days,
--     status,
--     reason,
--     approved_by,
--     approved_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO hr.leave_applications (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

