-- LeaveBalance Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the hr.leave_balances table.
-- Customize this file to add your initial data.

-- INSERT INTO hr.leave_balances (
--     id,
--     company_id,
--     employee_id,
--     leave_type_id,
--     year,
--     allocated,
--     used,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO hr.leave_balances (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

