-- Migration: Create employees table
-- Generated by metaphor-schema

-- Create employment_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employment_type') THEN
        CREATE TYPE employment_type AS ENUM ('permanent', 'contract', 'probation', 'intern');
    END IF;
END
$$;

-- Create employee_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'employee_status') THEN
        CREATE TYPE employee_status AS ENUM ('active', 'resigned', 'terminated');
    END IF;
END
$$;

-- Create tax_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tax_status') THEN
        CREATE TYPE tax_status AS ENUM ('tk0', 'tk1', 'tk2', 'tk3', 'k0', 'k1', 'k2', 'k3');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS hr;

CREATE TABLE IF NOT EXISTS hr.employees (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_number TEXT NOT NULL,
    user_id UUID,
    department_id UUID,
    first_name TEXT NOT NULL,
    last_name TEXT,
    designation TEXT,
    employment_type employment_type NOT NULL DEFAULT 'permanent',
    date_of_joining TIMESTAMPTZ NOT NULL,
    date_of_exit TIMESTAMPTZ,
    status employee_status NOT NULL DEFAULT 'active',
    nik TEXT,
    npwp TEXT,
    tax_status tax_status NOT NULL DEFAULT 'tk0',
    bank_account_no TEXT,
    base_salary NUMERIC NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_employees_company_id_status ON hr.employees (company_id, status);

CREATE INDEX IF NOT EXISTS idx_employees_department_id ON hr.employees (department_id);

CREATE INDEX IF NOT EXISTS idx_employees_user_id ON hr.employees (user_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_employees_metadata_gin ON hr.employees USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_employees_metadata_deleted_at ON hr.employees ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_employees_metadata_created_at ON hr.employees ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_employees_metadata_updated_at ON hr.employees ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION hr.employees_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employees_insert_audit ON hr.employees;
CREATE TRIGGER employees_insert_audit BEFORE INSERT ON hr.employees
    FOR EACH ROW EXECUTE FUNCTION hr.employees_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employees_update_audit ON hr.employees;
CREATE TRIGGER employees_update_audit BEFORE UPDATE ON hr.employees
    FOR EACH ROW EXECUTE FUNCTION hr.employees_audit_timestamp();
