-- Migration: Create leave_types table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS hr;

CREATE TABLE IF NOT EXISTS hr.leave_types (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    is_paid BOOLEAN NOT NULL DEFAULT TRUE,
    annual_quota_days NUMERIC(6, 2) NOT NULL DEFAULT 0 CHECK (annual_quota_days >= 0),
    allow_carry_forward BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_leave_types_company_id_is_active ON hr.leave_types (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_leave_types_metadata_gin ON hr.leave_types USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_leave_types_metadata_deleted_at ON hr.leave_types ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_leave_types_metadata_created_at ON hr.leave_types ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_leave_types_metadata_updated_at ON hr.leave_types ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION hr.leave_types_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS leave_types_insert_audit ON hr.leave_types;
CREATE TRIGGER leave_types_insert_audit BEFORE INSERT ON hr.leave_types
    FOR EACH ROW EXECUTE FUNCTION hr.leave_types_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS leave_types_update_audit ON hr.leave_types;
CREATE TRIGGER leave_types_update_audit BEFORE UPDATE ON hr.leave_types
    FOR EACH ROW EXECUTE FUNCTION hr.leave_types_audit_timestamp();
