-- Migration: Create leave_applications table
-- Generated by metaphor-schema

-- Create leave_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'leave_status') THEN
        CREATE TYPE leave_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS hr;

CREATE TABLE IF NOT EXISTS hr.leave_applications (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    leave_type_id UUID NOT NULL,
    from_date TIMESTAMPTZ NOT NULL,
    to_date TIMESTAMPTZ NOT NULL,
    days NUMERIC(6, 2) NOT NULL DEFAULT 0 CHECK (days >= 0),
    status leave_status NOT NULL DEFAULT 'pending',
    reason TEXT,
    approved_by UUID,
    approved_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_leave_applications_company_id_status ON hr.leave_applications (company_id, status);

CREATE INDEX IF NOT EXISTS idx_leave_applications_employee_id_status ON hr.leave_applications (employee_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_leave_applications_metadata_gin ON hr.leave_applications USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_leave_applications_metadata_deleted_at ON hr.leave_applications ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_leave_applications_metadata_created_at ON hr.leave_applications ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_leave_applications_metadata_updated_at ON hr.leave_applications ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION hr.leave_applications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS leave_applications_insert_audit ON hr.leave_applications;
CREATE TRIGGER leave_applications_insert_audit BEFORE INSERT ON hr.leave_applications
    FOR EACH ROW EXECUTE FUNCTION hr.leave_applications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS leave_applications_update_audit ON hr.leave_applications;
CREATE TRIGGER leave_applications_update_audit BEFORE UPDATE ON hr.leave_applications
    FOR EACH ROW EXECUTE FUNCTION hr.leave_applications_audit_timestamp();
