-- Audit Triggers Migration for hr module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Attendance (hr.attendances)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION hr.attendances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attendances_insert_audit ON hr.attendances;
CREATE TRIGGER attendances_insert_audit BEFORE INSERT ON hr.attendances
    FOR EACH ROW EXECUTE FUNCTION hr.attendances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attendances_update_audit ON hr.attendances;
CREATE TRIGGER attendances_update_audit BEFORE UPDATE ON hr.attendances
    FOR EACH ROW EXECUTE FUNCTION hr.attendances_audit_timestamp();

-- ==============================================================================
-- Table: Employee (hr.employees)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION hr.employees_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employees_insert_audit ON hr.employees;
CREATE TRIGGER employees_insert_audit BEFORE INSERT ON hr.employees
    FOR EACH ROW EXECUTE FUNCTION hr.employees_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employees_update_audit ON hr.employees;
CREATE TRIGGER employees_update_audit BEFORE UPDATE ON hr.employees
    FOR EACH ROW EXECUTE FUNCTION hr.employees_audit_timestamp();

-- ==============================================================================
-- Table: LeaveApplication (hr.leave_applications)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION hr.leave_applications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS leave_applications_insert_audit ON hr.leave_applications;
CREATE TRIGGER leave_applications_insert_audit BEFORE INSERT ON hr.leave_applications
    FOR EACH ROW EXECUTE FUNCTION hr.leave_applications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS leave_applications_update_audit ON hr.leave_applications;
CREATE TRIGGER leave_applications_update_audit BEFORE UPDATE ON hr.leave_applications
    FOR EACH ROW EXECUTE FUNCTION hr.leave_applications_audit_timestamp();

-- ==============================================================================
-- Table: LeaveBalance (hr.leave_balances)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION hr.leave_balances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS leave_balances_insert_audit ON hr.leave_balances;
CREATE TRIGGER leave_balances_insert_audit BEFORE INSERT ON hr.leave_balances
    FOR EACH ROW EXECUTE FUNCTION hr.leave_balances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS leave_balances_update_audit ON hr.leave_balances;
CREATE TRIGGER leave_balances_update_audit BEFORE UPDATE ON hr.leave_balances
    FOR EACH ROW EXECUTE FUNCTION hr.leave_balances_audit_timestamp();

-- ==============================================================================
-- Table: LeaveType (hr.leave_types)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION hr.leave_types_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS leave_types_insert_audit ON hr.leave_types;
CREATE TRIGGER leave_types_insert_audit BEFORE INSERT ON hr.leave_types
    FOR EACH ROW EXECUTE FUNCTION hr.leave_types_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS leave_types_update_audit ON hr.leave_types;
CREATE TRIGGER leave_types_update_audit BEFORE UPDATE ON hr.leave_types
    FOR EACH ROW EXECUTE FUNCTION hr.leave_types_audit_timestamp();

