-- Migration: Create attendances table
-- Generated by metaphor-schema

-- Create attendance_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendance_status') THEN
        CREATE TYPE attendance_status AS ENUM ('present', 'absent', 'half_day', 'on_leave', 'holiday');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS hr;

CREATE TABLE IF NOT EXISTS hr.attendances (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    attendance_date TIMESTAMPTZ NOT NULL,
    status attendance_status NOT NULL DEFAULT 'present',
    working_hours NUMERIC NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_attendances_employee_id_attendance_date ON hr.attendances (employee_id, attendance_date);

CREATE INDEX IF NOT EXISTS idx_attendances_company_id_attendance_date ON hr.attendances (company_id, attendance_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_attendances_metadata_gin ON hr.attendances USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_attendances_metadata_deleted_at ON hr.attendances ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_attendances_metadata_created_at ON hr.attendances ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_attendances_metadata_updated_at ON hr.attendances ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION hr.attendances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attendances_insert_audit ON hr.attendances;
CREATE TRIGGER attendances_insert_audit BEFORE INSERT ON hr.attendances
    FOR EACH ROW EXECUTE FUNCTION hr.attendances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attendances_update_audit ON hr.attendances;
CREATE TRIGGER attendances_update_audit BEFORE UPDATE ON hr.attendances
    FOR EACH ROW EXECUTE FUNCTION hr.attendances_audit_timestamp();
