-- Migration: Create leave_balances table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS hr;

CREATE TABLE IF NOT EXISTS hr.leave_balances (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    leave_type_id UUID NOT NULL,
    year INTEGER NOT NULL,
    allocated NUMERIC NOT NULL DEFAULT 0,
    used NUMERIC NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_leave_balances_employee_id_leave_type_id_year ON hr.leave_balances (employee_id, leave_type_id, year);

CREATE INDEX IF NOT EXISTS idx_leave_balances_company_id_year ON hr.leave_balances (company_id, year);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_leave_balances_metadata_gin ON hr.leave_balances USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_leave_balances_metadata_deleted_at ON hr.leave_balances ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_leave_balances_metadata_created_at ON hr.leave_balances ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_leave_balances_metadata_updated_at ON hr.leave_balances ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION hr.leave_balances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS leave_balances_insert_audit ON hr.leave_balances;
CREATE TRIGGER leave_balances_insert_audit BEFORE INSERT ON hr.leave_balances
    FOR EACH ROW EXECUTE FUNCTION hr.leave_balances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS leave_balances_update_audit ON hr.leave_balances;
CREATE TRIGGER leave_balances_update_audit BEFORE UPDATE ON hr.leave_balances
    FOR EACH ROW EXECUTE FUNCTION hr.leave_balances_audit_timestamp();
