-- Company RLS fence for hr module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for hr.attendances
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE hr.attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.attendances FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS attendances_company_isolation ON hr.attendances;
CREATE POLICY attendances_company_isolation ON hr.attendances
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for hr.employees
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE hr.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.employees FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employees_company_isolation ON hr.employees;
CREATE POLICY employees_company_isolation ON hr.employees
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for hr.leave_applications
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE hr.leave_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.leave_applications FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS leave_applications_company_isolation ON hr.leave_applications;
CREATE POLICY leave_applications_company_isolation ON hr.leave_applications
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for hr.leave_balances
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE hr.leave_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.leave_balances FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS leave_balances_company_isolation ON hr.leave_balances;
CREATE POLICY leave_balances_company_isolation ON hr.leave_balances
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for hr.leave_types
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE hr.leave_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr.leave_types FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS leave_types_company_isolation ON hr.leave_types;
CREATE POLICY leave_types_company_isolation ON hr.leave_types
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

