//! Event handler trait for Attendance events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AttendanceEvent;

/// Event handler for Attendance events.
/// Implement this trait to react to Attendance lifecycle events.
pub trait AttendanceEventHandler: EventHandler<AttendanceEvent> {}
