//! Domain events for Attendance entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Attendance;

/// Domain events for Attendance — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Attendance>)` variant.
pub type AttendanceEvent = CrudEvent<Attendance>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Attendance events.
pub type AttendanceEventPublisher = Arc<dyn CrudEventPublisher<Attendance> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAttendanceEventPublisher = NoOpCrudEventPublisher<Attendance>;
