//! Domain events for Employee entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Employee;

/// Domain events for Employee — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Employee>)` variant.
pub type EmployeeEvent = CrudEvent<Employee>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Employee events.
pub type EmployeeEventPublisher = Arc<dyn CrudEventPublisher<Employee> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEmployeeEventPublisher = NoOpCrudEventPublisher<Employee>;
