//! Event handler trait for Employee events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmployeeEvent;

/// Event handler for Employee events.
/// Implement this trait to react to Employee lifecycle events.
pub trait EmployeeEventHandler: EventHandler<EmployeeEvent> {}
