//! Event handler trait for LeaveBalance events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LeaveBalanceEvent;

/// Event handler for LeaveBalance events.
/// Implement this trait to react to LeaveBalance lifecycle events.
pub trait LeaveBalanceEventHandler: EventHandler<LeaveBalanceEvent> {}
