//! Event handler trait for LeaveType events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LeaveTypeEvent;

/// Event handler for LeaveType events.
/// Implement this trait to react to LeaveType lifecycle events.
pub trait LeaveTypeEventHandler: EventHandler<LeaveTypeEvent> {}
