//! Event handler trait for LeaveApplication events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LeaveApplicationEvent;

/// Event handler for LeaveApplication events.
/// Implement this trait to react to LeaveApplication lifecycle events.
pub trait LeaveApplicationEventHandler: EventHandler<LeaveApplicationEvent> {}
