//! Domain events for LeaveBalance entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::LeaveBalance;

/// Domain events for LeaveBalance — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<LeaveBalance>)` variant.
pub type LeaveBalanceEvent = CrudEvent<LeaveBalance>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for LeaveBalance events.
pub type LeaveBalanceEventPublisher = Arc<dyn CrudEventPublisher<LeaveBalance> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLeaveBalanceEventPublisher = NoOpCrudEventPublisher<LeaveBalance>;
