//! Domain events for LeaveType entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::LeaveType;

/// Domain events for LeaveType — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<LeaveType>)` variant.
pub type LeaveTypeEvent = CrudEvent<LeaveType>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for LeaveType events.
pub type LeaveTypeEventPublisher = Arc<dyn CrudEventPublisher<LeaveType> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLeaveTypeEventPublisher = NoOpCrudEventPublisher<LeaveType>;
