//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attendance_events;
pub mod attendance_event_handlers;
pub mod employee_events;
pub mod employee_event_handlers;
pub mod leave_application_events;
pub mod leave_application_event_handlers;
pub mod leave_balance_events;
pub mod leave_balance_event_handlers;
pub mod leave_type_events;
pub mod leave_type_event_handlers;

pub use attendance_events::{AttendanceEvent, AttendanceEventPublisher, NoopAttendanceEventPublisher};
pub use attendance_event_handlers::AttendanceEventHandler;
pub use employee_events::{EmployeeEvent, EmployeeEventPublisher, NoopEmployeeEventPublisher};
pub use employee_event_handlers::EmployeeEventHandler;
pub use leave_application_events::{LeaveApplicationEvent, LeaveApplicationEventPublisher, NoopLeaveApplicationEventPublisher};
pub use leave_application_event_handlers::LeaveApplicationEventHandler;
pub use leave_balance_events::{LeaveBalanceEvent, LeaveBalanceEventPublisher, NoopLeaveBalanceEventPublisher};
pub use leave_balance_event_handlers::LeaveBalanceEventHandler;
pub use leave_type_events::{LeaveTypeEvent, LeaveTypeEventPublisher, NoopLeaveTypeEventPublisher};
pub use leave_type_event_handlers::LeaveTypeEventHandler;

// <<< CUSTOM
// END CUSTOM
