//! Event subscriber type aliases for Hr module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::AttendanceEvent;
use crate::domain::event::EmployeeEvent;
use crate::domain::event::LeaveApplicationEvent;
use crate::domain::event::LeaveBalanceEvent;
use crate::domain::event::LeaveTypeEvent;

/// Subscriber for Attendance events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AttendanceEventSubscriber = GenericEventSubscriber<AttendanceEvent>;

/// Subscriber for Employee events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type EmployeeEventSubscriber = GenericEventSubscriber<EmployeeEvent>;

/// Subscriber for LeaveApplication events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type LeaveApplicationEventSubscriber = GenericEventSubscriber<LeaveApplicationEvent>;

/// Subscriber for LeaveBalance events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type LeaveBalanceEventSubscriber = GenericEventSubscriber<LeaveBalanceEvent>;

/// Subscriber for LeaveType events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type LeaveTypeEventSubscriber = GenericEventSubscriber<LeaveTypeEvent>;

// <<< CUSTOM
// END CUSTOM
