//! Employee seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Employee data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// EMPLOYEE SEEDER
// ============================================================================

/// Seeder for employee
pub struct SeedEmployeeSeeder;

impl SeedEmployeeSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedEmployeeSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedEmployeeSeeder {
    fn name(&self) -> &'static str {
        "SeedEmployeeSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if hr.employees table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM hr.employees")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/employee_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM hr.employees")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

