//! LeaveType seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial LeaveType data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// LEAVETYPE SEEDER
// ============================================================================

/// Seeder for leave_type
pub struct SeedLeaveTypeSeeder;

impl SeedLeaveTypeSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedLeaveTypeSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedLeaveTypeSeeder {
    fn name(&self) -> &'static str {
        "SeedLeaveTypeSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if hr.leave_types table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM hr.leave_types")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/leave_type_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM hr.leave_types")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

