//! Repository trait for Attendance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Attendance aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Attendance, AttendanceStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttendancePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AttendancePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AttendancePaginatedResult {
    pub data: Vec<Attendance>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttendanceFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub status: Option<AttendanceStatus>,
}

impl AttendanceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for Attendance aggregate
///
/// This trait defines the persistence contract for Attendance entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AttendanceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new attendance entity
    async fn save(&self, entity: &Attendance) -> Result<Attendance>;

    /// Find attendance by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Attendance>>;

    /// Find all attendance entities
    async fn find_all(&self) -> Result<Vec<Attendance>>;

    /// Update attendance by ID
    async fn update(&self, id: &str, entity: &Attendance) -> Result<Option<Attendance>>;

    /// Delete attendance by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List attendance with pagination
    async fn list(&self, params: AttendancePaginationParams) -> Result<AttendancePaginatedResult>;

    /// List attendance with pagination and filters
    async fn list_with_filters(&self, params: AttendancePaginationParams, filters: AttendanceFilter) -> Result<AttendancePaginatedResult>;

    /// Count all attendance entities
    async fn count(&self) -> Result<u64>;

    /// Count attendance entities matching filters
    async fn count_with_filters(&self, filters: AttendanceFilter) -> Result<u64>;

    /// Check if attendance exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete attendance by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted attendance by ID
    async fn restore(&self, id: &str) -> Result<Option<Attendance>>;

    /// List soft-deleted attendance entities
    async fn list_deleted(&self, params: AttendancePaginationParams) -> Result<AttendancePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save attendance entities
    async fn bulk_save(&self, entities: &[Attendance]) -> Result<Vec<Attendance>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
