//! Repository trait for Employee aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Employee aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Employee, EmployeeStatus, EmploymentType, TaxStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmployeePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmployeePaginatedResult {
    pub data: Vec<Employee>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeFilter {
    pub company_id: Option<Uuid>,
    pub employee_number: Option<String>,
    pub user_id: Option<Uuid>,
    pub department_id: Option<Uuid>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub designation: Option<String>,
    pub employment_type: Option<EmploymentType>,
    pub status: Option<EmployeeStatus>,
    pub nik: Option<String>,
    pub npwp: Option<String>,
    pub tax_status: Option<TaxStatus>,
    pub bank_account_no: Option<String>,
}

impl EmployeeFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_number.is_some() || self.user_id.is_some() || self.department_id.is_some() || self.first_name.is_some() || self.last_name.is_some() || self.designation.is_some() || self.employment_type.is_some() || self.status.is_some() || self.nik.is_some() || self.npwp.is_some() || self.tax_status.is_some() || self.bank_account_no.is_some()
    }
}

/// Repository trait for Employee aggregate
///
/// This trait defines the persistence contract for Employee entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmployeeRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new employee entity
    async fn save(&self, entity: &Employee) -> Result<Employee>;

    /// Find employee by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Employee>>;

    /// Find all employee entities
    async fn find_all(&self) -> Result<Vec<Employee>>;

    /// Update employee by ID
    async fn update(&self, id: &str, entity: &Employee) -> Result<Option<Employee>>;

    /// Delete employee by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List employee with pagination
    async fn list(&self, params: EmployeePaginationParams) -> Result<EmployeePaginatedResult>;

    /// List employee with pagination and filters
    async fn list_with_filters(&self, params: EmployeePaginationParams, filters: EmployeeFilter) -> Result<EmployeePaginatedResult>;

    /// Count all employee entities
    async fn count(&self) -> Result<u64>;

    /// Count employee entities matching filters
    async fn count_with_filters(&self, filters: EmployeeFilter) -> Result<u64>;

    /// Check if employee exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete employee by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted employee by ID
    async fn restore(&self, id: &str) -> Result<Option<Employee>>;

    /// List soft-deleted employee entities
    async fn list_deleted(&self, params: EmployeePaginationParams) -> Result<EmployeePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save employee entities
    async fn bulk_save(&self, entities: &[Employee]) -> Result<Vec<Employee>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
