//! Repository trait for LeaveApplication aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the LeaveApplication aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{LeaveApplication, LeaveStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LeaveApplicationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl LeaveApplicationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct LeaveApplicationPaginatedResult {
    pub data: Vec<LeaveApplication>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LeaveApplicationFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub leave_type_id: Option<Uuid>,
    pub status: Option<LeaveStatus>,
    pub reason: Option<String>,
    pub approved_by: Option<Uuid>,
}

impl LeaveApplicationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.leave_type_id.is_some() || self.status.is_some() || self.reason.is_some() || self.approved_by.is_some()
    }
}

/// Repository trait for LeaveApplication aggregate
///
/// This trait defines the persistence contract for LeaveApplication entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait LeaveApplicationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new leave_application entity
    async fn save(&self, entity: &LeaveApplication) -> Result<LeaveApplication>;

    /// Find leave_application by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<LeaveApplication>>;

    /// Find all leave_application entities
    async fn find_all(&self) -> Result<Vec<LeaveApplication>>;

    /// Update leave_application by ID
    async fn update(&self, id: &str, entity: &LeaveApplication) -> Result<Option<LeaveApplication>>;

    /// Delete leave_application by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List leave_application with pagination
    async fn list(&self, params: LeaveApplicationPaginationParams) -> Result<LeaveApplicationPaginatedResult>;

    /// List leave_application with pagination and filters
    async fn list_with_filters(&self, params: LeaveApplicationPaginationParams, filters: LeaveApplicationFilter) -> Result<LeaveApplicationPaginatedResult>;

    /// Count all leave_application entities
    async fn count(&self) -> Result<u64>;

    /// Count leave_application entities matching filters
    async fn count_with_filters(&self, filters: LeaveApplicationFilter) -> Result<u64>;

    /// Check if leave_application exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete leave_application by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted leave_application by ID
    async fn restore(&self, id: &str) -> Result<Option<LeaveApplication>>;

    /// List soft-deleted leave_application entities
    async fn list_deleted(&self, params: LeaveApplicationPaginationParams) -> Result<LeaveApplicationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save leave_application entities
    async fn bulk_save(&self, entities: &[LeaveApplication]) -> Result<Vec<LeaveApplication>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
