//! Repository trait for LeaveBalance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the LeaveBalance aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::LeaveBalance;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LeaveBalancePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl LeaveBalancePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct LeaveBalancePaginatedResult {
    pub data: Vec<LeaveBalance>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LeaveBalanceFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub leave_type_id: Option<Uuid>,
}

impl LeaveBalanceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.leave_type_id.is_some()
    }
}

/// Repository trait for LeaveBalance aggregate
///
/// This trait defines the persistence contract for LeaveBalance entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait LeaveBalanceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new leave_balance entity
    async fn save(&self, entity: &LeaveBalance) -> Result<LeaveBalance>;

    /// Find leave_balance by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<LeaveBalance>>;

    /// Find all leave_balance entities
    async fn find_all(&self) -> Result<Vec<LeaveBalance>>;

    /// Update leave_balance by ID
    async fn update(&self, id: &str, entity: &LeaveBalance) -> Result<Option<LeaveBalance>>;

    /// Delete leave_balance by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List leave_balance with pagination
    async fn list(&self, params: LeaveBalancePaginationParams) -> Result<LeaveBalancePaginatedResult>;

    /// List leave_balance with pagination and filters
    async fn list_with_filters(&self, params: LeaveBalancePaginationParams, filters: LeaveBalanceFilter) -> Result<LeaveBalancePaginatedResult>;

    /// Count all leave_balance entities
    async fn count(&self) -> Result<u64>;

    /// Count leave_balance entities matching filters
    async fn count_with_filters(&self, filters: LeaveBalanceFilter) -> Result<u64>;

    /// Check if leave_balance exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete leave_balance by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted leave_balance by ID
    async fn restore(&self, id: &str) -> Result<Option<LeaveBalance>>;

    /// List soft-deleted leave_balance entities
    async fn list_deleted(&self, params: LeaveBalancePaginationParams) -> Result<LeaveBalancePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save leave_balance entities
    async fn bulk_save(&self, entities: &[LeaveBalance]) -> Result<Vec<LeaveBalance>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
