//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod attendance_repository;
pub mod employee_repository;
pub mod leave_application_repository;
pub mod leave_balance_repository;
pub mod leave_type_repository;

// Re-exports
pub use attendance_repository::{
    AttendanceRepository,
    AttendancePaginationParams,
    AttendancePaginatedResult,
    AttendanceFilter,
};
pub use employee_repository::{
    EmployeeRepository,
    EmployeePaginationParams,
    EmployeePaginatedResult,
    EmployeeFilter,
};
pub use leave_application_repository::{
    LeaveApplicationRepository,
    LeaveApplicationPaginationParams,
    LeaveApplicationPaginatedResult,
    LeaveApplicationFilter,
};
pub use leave_balance_repository::{
    LeaveBalanceRepository,
    LeaveBalancePaginationParams,
    LeaveBalancePaginatedResult,
    LeaveBalanceFilter,
};
pub use leave_type_repository::{
    LeaveTypeRepository,
    LeaveTypePaginationParams,
    LeaveTypePaginatedResult,
    LeaveTypeFilter,
};
