//! Repository for Attendance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Attendance;

/// Table name for Attendance entities
pub const TABLE_NAME: &str = "hr.attendances";

/// Repository for Attendance entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AttendanceRepository(
    backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AttendanceRepository {
    type Target = backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AttendanceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AttendanceRepository, Attendance, soft_delete);
