//! Repository for Attendance entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Attendance SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Attendance;

/// Table name for Attendance entities
pub const TABLE_NAME: &str = "hr.attendances";

/// Repository for Attendance entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AttendanceRepository(
    backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AttendanceRepository {
    type Target = backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AttendanceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an attendance mark writes.
///
/// Mirrors the raw column shape rather than the `Attendance` entity: `status` is cast at the DB
/// (`$5::attendance_status`), which is what lets a bad variant fail as a DB error instead of a
/// deserialize panic.
pub struct NewAttendanceRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub attendance_date: DateTime<Utc>,
    pub status: &'a str,
    pub working_hours: Decimal,
}

/// Hand-written Attendance SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl AttendanceRepository {
    /// Record (or overwrite) an employee's attendance for a day — one record per (employee, date).
    /// Returns the surviving record's id, which on a re-mark is the ORIGINAL row's id, not `row.id`.
    ///
    /// A write outside any transaction: takes the pool and runs `fetch_one_scalar_scoped` so the RLS
    /// fence (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` using the
    /// company it read off the employee — that scope is what satisfies the upsert's WITH CHECK.
    pub async fn upsert_attendance(
        &self,
        pool: &PgPool,
        a: &NewAttendanceRow<'_>,
    ) -> Result<Uuid, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"INSERT INTO hr.attendances (id, company_id, employee_id, attendance_date, status, working_hours)
                   VALUES ($1,$2,$3,$4,$5::attendance_status,$6)
                   ON CONFLICT (employee_id, attendance_date)
                   DO UPDATE SET status=EXCLUDED.status, working_hours=EXCLUDED.working_hours
                   RETURNING id"#,
            )
            .bind(a.id).bind(a.company_id).bind(a.employee_id).bind(a.attendance_date)
            .bind(a.status).bind(a.working_hours),
        )
        .await
    }

    /// Count attendance absences over `[from, to]` (inclusive dates) that are NOT already covered by an
    /// approved leave — so leave and attendance never double-count the same day against pay.
    ///
    /// ID-only, read-only: identified by employee id alone, riding the request-dedicated connection. An
    /// event/job caller must wrap this in `with_company_scope(Some(company_id))`, otherwise it fails
    /// closed (0 rows).
    pub async fn count_uncovered_absences(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
        from: DateTime<Utc>,
        to: DateTime<Utc>,
    ) -> Result<i64, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar(
            r#"SELECT count(*) FROM hr.attendances a
               WHERE a.employee_id=$1 AND a.attendance_date::date BETWEEN $2::date AND $3::date
                 AND a.status='absent'::attendance_status AND (a.metadata->>'deleted_at') IS NULL
                 AND NOT EXISTS (
                   SELECT 1 FROM hr.leave_applications la
                   WHERE la.employee_id=$1 AND la.status='approved'::leave_status
                     AND a.attendance_date::date BETWEEN la.from_date::date AND la.to_date::date)"#,
            )
            .bind(employee_id).bind(from).bind(to),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(AttendanceRepository, Attendance, soft_delete);
