//! Repository for Employee entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Employee SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Employee, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Employee;

/// Table name for Employee entities
pub const TABLE_NAME: &str = "hr.employees";

/// Repository for Employee entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmployeeRepository(
    backbone_orm::GenericCrudRepository<Employee, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmployeeRepository {
    type Target = backbone_orm::GenericCrudRepository<Employee, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmployeeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an onboarding insert writes.
///
/// Mirrors the raw column shape rather than the `Employee` entity: `employment_type`/`tax_status`
/// arrive as free strings and are cast at the DB (`$9::employment_type`, `$13::tax_status`), which is
/// what lets a bad variant fail as a DB error instead of a deserialize panic.
pub struct NewEmployeeRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_number: &'a str,
    pub user_id: Option<Uuid>,
    pub department_id: Option<Uuid>,
    pub first_name: &'a str,
    pub last_name: Option<&'a str>,
    pub designation: Option<&'a str>,
    pub employment_type: &'a str,
    pub date_of_joining: DateTime<Utc>,
    pub nik: Option<&'a str>,
    pub npwp: Option<&'a str>,
    pub tax_status: &'a str,
    pub bank_account_no: Option<&'a str>,
    pub base_salary: Decimal,
}

/// A live employee's company + roster state — what the leave path reads before it writes.
pub struct EmployeeScopeRow {
    pub company_id: Uuid,
    pub status: String,
}

/// Hand-written Employee SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl EmployeeRepository {
    /// Probe for a live employee already holding this number in the company — the per-company
    /// `employee_number` uniqueness gate.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_optional_scalar_scoped` so the
    /// RLS fence (ADR-0008) applies. The caller binds the company (it is on the DTO); the explicit
    /// `company_id = $1` filter stays as defense-in-depth.
    pub async fn find_live_id_by_number(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        employee_number: &str,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT id FROM hr.employees WHERE company_id=$1 AND employee_number=$2
                   AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(company_id).bind(employee_number),
        )
        .await
    }

    /// Onboard an employee onto the roster as `active`. Caller supplies the company scope, as above.
    pub async fn insert_employee(
        &self,
        pool: &PgPool,
        e: &NewEmployeeRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO hr.employees
                     (id, company_id, employee_number, user_id, department_id, first_name, last_name,
                      designation, employment_type, date_of_joining, status, nik, npwp, tax_status,
                      bank_account_no, base_salary)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::employment_type,$10,'active'::employee_status,
                           $11,$12,$13::tax_status,$14,$15)"#,
            )
            .bind(e.id).bind(e.company_id).bind(e.employee_number).bind(e.user_id).bind(e.department_id)
            .bind(e.first_name).bind(e.last_name).bind(e.designation).bind(e.employment_type)
            .bind(e.date_of_joining).bind(e.nik).bind(e.npwp).bind(e.tax_status).bind(e.bank_account_no)
            .bind(e.base_salary),
        )
        .await?;
        Ok(())
    }

    /// Stop an active employee's roster (resign/terminate), returning their `company_id` so the caller
    /// can announce the exit. `Ok(None)` = no such ACTIVE employee in scope.
    ///
    /// ID-only: no company argument. `fetch_optional_row_scoped` means it rides a connection carrying
    /// the caller's `app.company_id`, so another company's employee simply is not matched.
    pub async fn exit_employee(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
        status: &str,
        exit_date: DateTime<Utc>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE hr.employees SET status=$2::employee_status, date_of_exit=$3
                   WHERE id=$1 AND status='active'::employee_status AND (metadata->>'deleted_at') IS NULL
                   RETURNING company_id"#,
            )
            .bind(employee_id).bind(status).bind(exit_date),
        )
        .await?;
        Ok(row.map(|r| r.get("company_id")))
    }

    /// Read a live employee's company + roster state — the leave applicant lookup.
    ///
    /// ID-only, same fencing as [`Self::exit_employee`]. The company comes back on the row precisely so
    /// the caller can bind the follow-on write to it explicitly.
    pub async fn find_scope_by_id(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
    ) -> Result<Option<EmployeeScopeRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, status::text AS status FROM hr.employees
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(employee_id),
        )
        .await?;
        Ok(row.map(|r| EmployeeScopeRow { company_id: r.get("company_id"), status: r.get("status") }))
    }

    /// Read just a live employee's company — the attendance path's scope lookup. ID-only, as above.
    pub async fn find_company_by_id(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT company_id FROM hr.employees WHERE id=$1 AND (metadata->>'deleted_at') IS NULL")
                .bind(employee_id),
        )
        .await?;
        Ok(row.map(|r| r.get("company_id")))
    }
}

backbone_core::impl_crud_repository!(EmployeeRepository, Employee, soft_delete);
