//! Repository for LeaveBalance entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written LeaveBalance SQL — the module's load-bearing invariant (4-layer rule:
//! services orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<LeaveBalance, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::LeaveBalance;

/// Table name for LeaveBalance entities
pub const TABLE_NAME: &str = "hr.leave_balances";

/// Repository for LeaveBalance entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct LeaveBalanceRepository(
    backbone_orm::GenericCrudRepository<LeaveBalance, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for LeaveBalanceRepository {
    type Target = backbone_orm::GenericCrudRepository<LeaveBalance, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl LeaveBalanceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a leave allocation writes. Mirrors the raw column shape, not the `LeaveBalance`
/// entity: the insert seeds `used = 0`, so that column is not a parameter, and `allocated` is bound
/// once but read twice by the statement (the VALUES and the DO UPDATE's `used <= $6` gate).
pub struct NewAllocationRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub leave_type_id: Uuid,
    pub year: i32,
    pub allocated: Decimal,
}

/// Hand-written LeaveBalance SQL — the leave-balance engine. Lives here (not in the write service) per
/// the module's 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl LeaveBalanceRepository {
    /// Set an employee's entitlement for a (type, year), idempotently. Returns rows affected: 0 = the
    /// new allocation is below what has already been used, so the DO UPDATE's gate refused it.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — that scope is
    /// what satisfies the INSERT's WITH CHECK.
    pub async fn upsert_allocation(
        &self,
        pool: &PgPool,
        b: &NewAllocationRow,
    ) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO hr.leave_balances (id, company_id, employee_id, leave_type_id, year, allocated, used)
                   VALUES ($1,$2,$3,$4,$5,$6,0)
                   ON CONFLICT (employee_id, leave_type_id, year)
                   DO UPDATE SET allocated = $6
                   WHERE hr.leave_balances.used <= $6"#,
            )
            .bind(b.id).bind(b.company_id).bind(b.employee_id).bind(b.leave_type_id).bind(b.year).bind(b.allocated),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// Draw down a balance on approval, GATED on availability: the row moves only if
    /// `used + days <= allocated`. Returns rows affected: 0 = insufficient (or missing) balance, and the
    /// caller must roll back. This gate IS the invariant — you cannot approve leave you don't have.
    ///
    /// Takes the CALLER'S connection so the draw and the application's `pending → approved` transition
    /// commit as ONE unit. The caller has already bound the company on it (`bind_company_on`) — don't
    /// re-bind here.
    pub async fn draw(
        &self,
        conn: &mut sqlx::PgConnection,
        employee_id: Uuid,
        leave_type_id: Uuid,
        year: i32,
        days: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE hr.leave_balances SET used = used + $4
               WHERE employee_id=$1 AND leave_type_id=$2 AND year=$3 AND used + $4 <= allocated"#,
        )
        .bind(employee_id).bind(leave_type_id).bind(year).bind(days)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Restore a drawn-down balance on cancellation. Returns rows affected: 0 = the caller must roll back.
    ///
    /// GATED on `used >= days` so a tampered application (its `days` mutated after approval via the
    /// generic PATCH surface) can never drive `used` negative and manufacture phantom entitlement
    /// (maturity council 2026-07-08). The DB CHECK `used >= 0` is the backstop for any other writer;
    /// this gate turns the violation into a clean domain error instead of a raw error.
    ///
    /// Same caller-owned-tx contract as [`Self::draw`]: the restore and the transition are one unit.
    pub async fn restore(
        &self,
        conn: &mut sqlx::PgConnection,
        employee_id: Uuid,
        leave_type_id: Uuid,
        year: i32,
        days: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE hr.leave_balances SET used = used - $4
               WHERE employee_id=$1 AND leave_type_id=$2 AND year=$3 AND used >= $4"#,
        )
        .bind(employee_id).bind(leave_type_id).bind(year).bind(days)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(LeaveBalanceRepository, LeaveBalance, soft_delete);
