//! Repository for LeaveType entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written LeaveType SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<LeaveType, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::LeaveType;

/// Table name for LeaveType entities
pub const TABLE_NAME: &str = "hr.leave_types";

/// Repository for LeaveType entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct LeaveTypeRepository(
    backbone_orm::GenericCrudRepository<LeaveType, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for LeaveTypeRepository {
    type Target = backbone_orm::GenericCrudRepository<LeaveType, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl LeaveTypeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a leave-type definition writes. Mirrors the raw column shape, not the `LeaveType`
/// entity — the insert hard-codes `is_active = true`, so that column is not a parameter.
pub struct NewLeaveTypeRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: &'a str,
    pub is_paid: bool,
    pub annual_quota_days: Decimal,
    pub allow_carry_forward: bool,
}

/// Hand-written LeaveType SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl LeaveTypeRepository {
    /// Define a leave type, active from the start.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK.
    pub async fn insert_leave_type(
        &self,
        pool: &PgPool,
        t: &NewLeaveTypeRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO hr.leave_types (id, company_id, name, is_paid, annual_quota_days, allow_carry_forward, is_active)
                   VALUES ($1,$2,$3,$4,$5,$6,true)"#,
            )
            .bind(t.id).bind(t.company_id).bind(t.name).bind(t.is_paid).bind(t.annual_quota_days).bind(t.allow_carry_forward),
        )
        .await?;
        Ok(())
    }

    /// Read a leave type's active flag. `Ok(None)` = no such type in the company.
    ///
    /// A read outside any transaction; the caller supplies the company scope. The explicit
    /// `company_id = $2` filter stays as defense-in-depth.
    pub async fn find_is_active(
        &self,
        pool: &PgPool,
        leave_type_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<bool>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT is_active FROM hr.leave_types WHERE id=$1 AND company_id=$2")
                .bind(leave_type_id).bind(company_id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(LeaveTypeRepository, LeaveType, soft_delete);
