//! Repository for LeaveApplication entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written LeaveApplication SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<LeaveApplication, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::LeaveApplication;

/// Table name for LeaveApplication entities
pub const TABLE_NAME: &str = "hr.leave_applications";

/// Repository for LeaveApplication entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct LeaveApplicationRepository(
    backbone_orm::GenericCrudRepository<LeaveApplication, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for LeaveApplicationRepository {
    type Target = backbone_orm::GenericCrudRepository<LeaveApplication, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl LeaveApplicationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a leave request writes. Mirrors the raw column shape, not the `LeaveApplication`
/// entity: `days` is the service-computed inclusive span and `status` is hard-coded `pending`, so
/// neither is a free parameter.
pub struct NewLeaveApplicationRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub leave_type_id: Uuid,
    pub from_date: DateTime<Utc>,
    pub to_date: DateTime<Utc>,
    pub days: Decimal,
    pub reason: Option<&'a str>,
}

/// What the approval path reads before it draws: the application joined to its type, carrying the
/// company that binds the transaction and the `is_paid` polarity the event announces.
pub struct LeaveApprovalRow {
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub leave_type_id: Uuid,
    pub days: Decimal,
    pub from_date: DateTime<Utc>,
    pub status: String,
    pub is_paid: bool,
}

/// What the cancellation path reads before it restores.
pub struct LeaveCancelRow {
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub leave_type_id: Uuid,
    pub days: Decimal,
    pub from_date: DateTime<Utc>,
    pub status: String,
}

/// One `is_paid` bucket of approved leave days clamped to a pay period.
pub struct LeaveDaysRow {
    pub is_paid: bool,
    pub days: Decimal,
}

/// Hand-written LeaveApplication SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl LeaveApplicationRepository {
    /// File a leave request as `pending`.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` using the
    /// company it read off the employee — that scope is what satisfies the INSERT's WITH CHECK.
    pub async fn insert_application(
        &self,
        pool: &PgPool,
        a: &NewLeaveApplicationRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO hr.leave_applications
                     (id, company_id, employee_id, leave_type_id, from_date, to_date, days, status, reason)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,'pending'::leave_status,$8)"#,
            )
            .bind(a.id).bind(a.company_id).bind(a.employee_id).bind(a.leave_type_id).bind(a.from_date)
            .bind(a.to_date).bind(a.days).bind(a.reason),
        )
        .await?;
        Ok(())
    }

    /// Read an application + its type for approval. `Ok(None)` = no such live application in scope.
    ///
    /// ID-only: no company argument. `fetch_optional_row_scoped` means it rides a connection carrying
    /// the caller's `app.company_id`, so another company's application simply is not found. The company
    /// comes back on the row precisely so the caller can bind the approval transaction to it explicitly
    /// — which is what fences the transition + draw even for non-request callers.
    pub async fn find_for_approval(
        &self,
        pool: &PgPool,
        leave_application_id: Uuid,
    ) -> Result<Option<LeaveApprovalRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT la.company_id, la.employee_id, la.leave_type_id, la.days, la.from_date,
                          la.status::text AS status, lt.is_paid
                   FROM hr.leave_applications la JOIN hr.leave_types lt ON lt.id = la.leave_type_id
                   WHERE la.id=$1 AND (la.metadata->>'deleted_at') IS NULL"#,
            )
            .bind(leave_application_id),
        )
        .await?;
        Ok(row.map(|r| LeaveApprovalRow {
            company_id: r.get("company_id"), employee_id: r.get("employee_id"),
            leave_type_id: r.get("leave_type_id"), days: r.get("days"), from_date: r.get("from_date"),
            status: r.get("status"), is_paid: r.get("is_paid"),
        }))
    }

    /// Claim the `pending → approved` transition (write-once). Returns rows affected: 0 = someone else
    /// already moved it and the caller must roll back.
    ///
    /// Takes the CALLER'S connection so this and the balance draw commit as ONE unit — the module's
    /// load-bearing invariant. The caller has already bound the company on it — don't re-bind here.
    pub async fn mark_approved(
        &self,
        conn: &mut sqlx::PgConnection,
        leave_application_id: Uuid,
        approver: Option<Uuid>,
        now: DateTime<Utc>,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE hr.leave_applications
               SET status='approved'::leave_status, approved_by=$2, approved_at=$3
               WHERE id=$1 AND status='pending'::leave_status"#,
        )
        .bind(leave_application_id).bind(approver).bind(now)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Reject a pending application (no balance change). Returns rows affected: 0 = not pending.
    ///
    /// ID-only: no company argument — `execute_scoped` rides the request-dedicated connection, so
    /// another company's application is simply not matched.
    pub async fn mark_rejected(
        &self,
        pool: &PgPool,
        leave_application_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE hr.leave_applications SET status='rejected'::leave_status
                   WHERE id=$1 AND status='pending'::leave_status AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(leave_application_id),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// Read an application for cancellation. `Ok(None)` = no such live application in scope.
    ///
    /// ID-only, fenced as [`Self::find_for_approval`]. The projection carries `company_id` deliberately:
    /// the restore transaction below binds it explicitly, which is what makes the invariant-critical
    /// path correct for non-request callers too.
    pub async fn find_for_cancel(
        &self,
        pool: &PgPool,
        leave_application_id: Uuid,
    ) -> Result<Option<LeaveCancelRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, employee_id, leave_type_id, days, from_date, status::text AS status
                   FROM hr.leave_applications WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(leave_application_id),
        )
        .await?;
        Ok(row.map(|r| LeaveCancelRow {
            company_id: r.get("company_id"), employee_id: r.get("employee_id"),
            leave_type_id: r.get("leave_type_id"), days: r.get("days"), from_date: r.get("from_date"),
            status: r.get("status"),
        }))
    }

    /// Cancel a PENDING application — nothing was drawn, so there is no balance to restore and no
    /// transaction to own. Returns rows affected: 0 = not cancellable. ID-only, as above.
    pub async fn cancel_pending(
        &self,
        pool: &PgPool,
        leave_application_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                "UPDATE hr.leave_applications SET status='cancelled'::leave_status WHERE id=$1 AND status='pending'::leave_status")
                .bind(leave_application_id),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// Cancel an APPROVED application. Returns rows affected: 0 = not approved, caller must roll back.
    ///
    /// Takes the CALLER'S connection so this and the balance restore commit as ONE unit (a balance is
    /// never left short). The caller has already bound the company on it — don't re-bind here.
    pub async fn cancel_approved(
        &self,
        conn: &mut sqlx::PgConnection,
        leave_application_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE hr.leave_applications SET status='cancelled'::leave_status
               WHERE id=$1 AND status='approved'::leave_status"#,
        )
        .bind(leave_application_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Sum approved leave days over `[from, to]` (inclusive dates), clamped to the period and split by
    /// the type's `is_paid` — the authoritative leave half of the payroll-facing period summary.
    ///
    /// ID-only, read-only: identified by employee id alone, riding the request-dedicated connection. An
    /// event/job caller must wrap this in `with_company_scope(Some(company_id))`, otherwise it fails
    /// closed (0 rows).
    pub async fn sum_approved_days_by_paid(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
        from: DateTime<Utc>,
        to: DateTime<Utc>,
    ) -> Result<Vec<LeaveDaysRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
            r#"SELECT lt.is_paid,
                      COALESCE(SUM(GREATEST(0, (LEAST(la.to_date::date, $3::date)
                                              - GREATEST(la.from_date::date, $2::date) + 1))), 0)::numeric AS days
               FROM hr.leave_applications la JOIN hr.leave_types lt ON lt.id = la.leave_type_id
               WHERE la.employee_id=$1 AND la.status='approved'::leave_status
                 AND (la.metadata->>'deleted_at') IS NULL
                 AND la.from_date::date <= $3::date AND la.to_date::date >= $2::date
               GROUP BY lt.is_paid"#,
            )
            .bind(employee_id).bind(from).bind(to),
        )
        .await?;
        Ok(rows.iter().map(|r| LeaveDaysRow { is_paid: r.get("is_paid"), days: r.get("days") }).collect())
    }
}

backbone_core::impl_crud_repository!(LeaveApplicationRepository, LeaveApplication, soft_delete);
