//! Repository for LeaveApplication entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<LeaveApplication, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::LeaveApplication;

/// Table name for LeaveApplication entities
pub const TABLE_NAME: &str = "hr.leave_applications";

/// Repository for LeaveApplication entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct LeaveApplicationRepository(
    backbone_orm::GenericCrudRepository<LeaveApplication, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for LeaveApplicationRepository {
    type Target = backbone_orm::GenericCrudRepository<LeaveApplication, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl LeaveApplicationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(LeaveApplicationRepository, LeaveApplication, soft_delete);
