//! Repository for LeaveBalance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<LeaveBalance, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::LeaveBalance;

/// Table name for LeaveBalance entities
pub const TABLE_NAME: &str = "hr.leave_balances";

/// Repository for LeaveBalance entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct LeaveBalanceRepository(
    backbone_orm::GenericCrudRepository<LeaveBalance, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for LeaveBalanceRepository {
    type Target = backbone_orm::GenericCrudRepository<LeaveBalance, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl LeaveBalanceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(LeaveBalanceRepository, LeaveBalance, soft_delete);
