//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod attendance_repository;
mod employee_repository;
mod leave_application_repository;
mod leave_balance_repository;
mod leave_type_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use attendance_repository::AttendanceRepository;
pub use employee_repository::EmployeeRepository;
pub use leave_application_repository::LeaveApplicationRepository;
pub use leave_balance_repository::LeaveBalanceRepository;
pub use leave_type_repository::LeaveTypeRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
