//! Validator for Attendance entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Attendance>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::Attendance;

/// Validator type alias for Attendance entities.
pub type AttendanceValidator = EntityValidator<Attendance>;

/// Build a validator for Attendance with all schema-defined field rules.
pub fn attendance_validator() -> AttendanceValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
