//! Validator for Employee entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Employee>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Employee;

/// Validator type alias for Employee entities.
pub type EmployeeValidator = EntityValidator<Employee>;

/// Build a validator for Employee with all schema-defined field rules.
pub fn employee_validator() -> EmployeeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("employee_number", |e: &Employee| &e.employee_number))
        .rule(RequiredString::new("first_name", |e: &Employee| &e.first_name))
        .rule(OptionalNotBlank::new("last_name", |e: &Employee| e.last_name.as_deref()))
        .rule(OptionalNotBlank::new("designation", |e: &Employee| e.designation.as_deref()))
        .rule(OptionalNotBlank::new("nik", |e: &Employee| e.nik.as_deref()))
        .rule(OptionalNotBlank::new("npwp", |e: &Employee| e.npwp.as_deref()))
        .rule(OptionalNotBlank::new("bank_account_no", |e: &Employee| e.bank_account_no.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
