//! Validator for LeaveApplication entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<LeaveApplication>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::LeaveApplication;

/// Validator type alias for LeaveApplication entities.
pub type LeaveApplicationValidator = EntityValidator<LeaveApplication>;

/// Build a validator for LeaveApplication with all schema-defined field rules.
pub fn leave_application_validator() -> LeaveApplicationValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("reason", |e: &LeaveApplication| e.reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
