//! Validator for LeaveBalance entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<LeaveBalance>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::LeaveBalance;

/// Validator type alias for LeaveBalance entities.
pub type LeaveBalanceValidator = EntityValidator<LeaveBalance>;

/// Build a validator for LeaveBalance with all schema-defined field rules.
pub fn leave_balance_validator() -> LeaveBalanceValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
