//! Validator for LeaveType entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<LeaveType>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::LeaveType;

/// Validator type alias for LeaveType entities.
pub type LeaveTypeValidator = EntityValidator<LeaveType>;

/// Build a validator for LeaveType with all schema-defined field rules.
pub fn leave_type_validator() -> LeaveTypeValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &LeaveType| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
