//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod attendance_validator;
pub mod employee_validator;
pub mod leave_application_validator;
pub mod leave_balance_validator;
pub mod leave_type_validator;

pub use attendance_validator::{AttendanceValidator, attendance_validator};
pub use employee_validator::{EmployeeValidator, employee_validator};
pub use leave_application_validator::{LeaveApplicationValidator, leave_application_validator};
pub use leave_balance_validator::{LeaveBalanceValidator, leave_balance_validator};
pub use leave_type_validator::{LeaveTypeValidator, leave_type_validator};

// <<< CUSTOM
// END CUSTOM
