//! Auth configuration for Attendance handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Attendance>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AttendanceService;
use crate::domain::entity::Attendance;

/// Permission string constants for Attendance operations.
pub mod permissions {
    pub const LIST:        &str = "attendance:list";
    pub const READ:        &str = "attendance:read";
    pub const CREATE:      &str = "attendance:create";
    pub const UPDATE:      &str = "attendance:update";
    pub const DELETE:      &str = "attendance:delete";
    pub const RESTORE:     &str = "attendance:restore";
    pub const TRASH:       &str = "attendance:trash";
    pub const EMPTY_TRASH: &str = "attendance:empty_trash";
    pub const BULK_CREATE: &str = "attendance:bulk_create";
    pub const UPSERT:      &str = "attendance:upsert";
}

/// Resource policy for Attendance — maps CRUD actions to permission strings.
pub struct AttendancePolicy;

#[async_trait]
impl ResourcePolicy<Attendance> for AttendancePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Attendance,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Attendance handlers.
///
/// Wraps `AttendanceService` and checks `AttendancePolicy` before delegating.
pub type AttendanceGuard = PermissionGuard<Attendance>;

/// Service-integrated permission guard for Attendance (for use in generated handlers).
pub type AttendanceServiceGuard = ServicePermissionGuard<Attendance, AttendanceService, AttendancePolicy>;

// <<< CUSTOM
// END CUSTOM
