//! Auth configuration for Employee handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Employee>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeService;
use crate::domain::entity::Employee;

/// Permission string constants for Employee operations.
pub mod permissions {
    pub const LIST:        &str = "employee:list";
    pub const READ:        &str = "employee:read";
    pub const CREATE:      &str = "employee:create";
    pub const UPDATE:      &str = "employee:update";
    pub const DELETE:      &str = "employee:delete";
    pub const RESTORE:     &str = "employee:restore";
    pub const TRASH:       &str = "employee:trash";
    pub const EMPTY_TRASH: &str = "employee:empty_trash";
    pub const BULK_CREATE: &str = "employee:bulk_create";
    pub const UPSERT:      &str = "employee:upsert";
}

/// Resource policy for Employee — maps CRUD actions to permission strings.
pub struct EmployeePolicy;

#[async_trait]
impl ResourcePolicy<Employee> for EmployeePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Employee,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Employee handlers.
///
/// Wraps `EmployeeService` and checks `EmployeePolicy` before delegating.
pub type EmployeeGuard = PermissionGuard<Employee>;

/// Service-integrated permission guard for Employee (for use in generated handlers).
pub type EmployeeServiceGuard = ServicePermissionGuard<Employee, EmployeeService, EmployeePolicy>;

// <<< CUSTOM
// END CUSTOM
