//! Auth configuration for LeaveApplication handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<LeaveApplication>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::LeaveApplicationService;
use crate::domain::entity::LeaveApplication;

/// Permission string constants for LeaveApplication operations.
pub mod permissions {
    pub const LIST:        &str = "leave_application:list";
    pub const READ:        &str = "leave_application:read";
    pub const CREATE:      &str = "leave_application:create";
    pub const UPDATE:      &str = "leave_application:update";
    pub const DELETE:      &str = "leave_application:delete";
    pub const RESTORE:     &str = "leave_application:restore";
    pub const TRASH:       &str = "leave_application:trash";
    pub const EMPTY_TRASH: &str = "leave_application:empty_trash";
    pub const BULK_CREATE: &str = "leave_application:bulk_create";
    pub const UPSERT:      &str = "leave_application:upsert";
}

/// Resource policy for LeaveApplication — maps CRUD actions to permission strings.
pub struct LeaveApplicationPolicy;

#[async_trait]
impl ResourcePolicy<LeaveApplication> for LeaveApplicationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &LeaveApplication,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for LeaveApplication handlers.
///
/// Wraps `LeaveApplicationService` and checks `LeaveApplicationPolicy` before delegating.
pub type LeaveApplicationGuard = PermissionGuard<LeaveApplication>;

/// Service-integrated permission guard for LeaveApplication (for use in generated handlers).
pub type LeaveApplicationServiceGuard = ServicePermissionGuard<LeaveApplication, LeaveApplicationService, LeaveApplicationPolicy>;

// <<< CUSTOM
// END CUSTOM
