//! Auth configuration for LeaveType handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<LeaveType>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::LeaveTypeService;
use crate::domain::entity::LeaveType;

/// Permission string constants for LeaveType operations.
pub mod permissions {
    pub const LIST:        &str = "leave_type:list";
    pub const READ:        &str = "leave_type:read";
    pub const CREATE:      &str = "leave_type:create";
    pub const UPDATE:      &str = "leave_type:update";
    pub const DELETE:      &str = "leave_type:delete";
    pub const RESTORE:     &str = "leave_type:restore";
    pub const TRASH:       &str = "leave_type:trash";
    pub const EMPTY_TRASH: &str = "leave_type:empty_trash";
    pub const BULK_CREATE: &str = "leave_type:bulk_create";
    pub const UPSERT:      &str = "leave_type:upsert";
}

/// Resource policy for LeaveType — maps CRUD actions to permission strings.
pub struct LeaveTypePolicy;

#[async_trait]
impl ResourcePolicy<LeaveType> for LeaveTypePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &LeaveType,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for LeaveType handlers.
///
/// Wraps `LeaveTypeService` and checks `LeaveTypePolicy` before delegating.
pub type LeaveTypeGuard = PermissionGuard<LeaveType>;

/// Service-integrated permission guard for LeaveType (for use in generated handlers).
pub type LeaveTypeServiceGuard = ServicePermissionGuard<LeaveType, LeaveTypeService, LeaveTypePolicy>;

// <<< CUSTOM
// END CUSTOM
