//! Auth configuration for LeaveBalance handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<LeaveBalance>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::LeaveBalanceService;
use crate::domain::entity::LeaveBalance;

/// Permission string constants for LeaveBalance operations.
pub mod permissions {
    pub const LIST:        &str = "leave_balance:list";
    pub const READ:        &str = "leave_balance:read";
    pub const CREATE:      &str = "leave_balance:create";
    pub const UPDATE:      &str = "leave_balance:update";
    pub const DELETE:      &str = "leave_balance:delete";
    pub const RESTORE:     &str = "leave_balance:restore";
    pub const TRASH:       &str = "leave_balance:trash";
    pub const EMPTY_TRASH: &str = "leave_balance:empty_trash";
    pub const BULK_CREATE: &str = "leave_balance:bulk_create";
    pub const UPSERT:      &str = "leave_balance:upsert";
}

/// Resource policy for LeaveBalance — maps CRUD actions to permission strings.
pub struct LeaveBalancePolicy;

#[async_trait]
impl ResourcePolicy<LeaveBalance> for LeaveBalancePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &LeaveBalance,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for LeaveBalance handlers.
///
/// Wraps `LeaveBalanceService` and checks `LeaveBalancePolicy` before delegating.
pub type LeaveBalanceGuard = PermissionGuard<LeaveBalance>;

/// Service-integrated permission guard for LeaveBalance (for use in generated handlers).
pub type LeaveBalanceServiceGuard = ServicePermissionGuard<LeaveBalance, LeaveBalanceService, LeaveBalancePolicy>;

// <<< CUSTOM
// END CUSTOM
