//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attendance_auth;
pub mod employee_auth;
pub mod leave_application_auth;
pub mod leave_balance_auth;
pub mod leave_type_auth;

pub use attendance_auth::{AttendancePolicy, AttendanceGuard, AttendanceServiceGuard};
pub use employee_auth::{EmployeePolicy, EmployeeGuard, EmployeeServiceGuard};
pub use leave_application_auth::{LeaveApplicationPolicy, LeaveApplicationGuard, LeaveApplicationServiceGuard};
pub use leave_balance_auth::{LeaveBalancePolicy, LeaveBalanceGuard, LeaveBalanceServiceGuard};
pub use leave_type_auth::{LeaveTypePolicy, LeaveTypeGuard, LeaveTypeServiceGuard};

// <<< CUSTOM
// END CUSTOM
