//! Attendance API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Attendance CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ATTENDANCE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Attendance
pub struct AttendanceTestData;

impl TestDataGenerator for AttendanceTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "attendance_date": now,
            "status": "present",
            "working_hours": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "attendance_date": now,
            "status": "present",
            "working_hours": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/employees", &super::employee_api_test::EmployeeTestData).await {
            deps.push(("employee_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ATTENDANCE API TEST
// ============================================================================

/// Attendance API test suite
pub struct AttendanceApiTest {
    inner: GenericCrudTest<AttendanceTestData>,
}

impl AttendanceApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/attendances", "Attendance");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AttendanceTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AttendanceApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_attendance_crud() {
        let mut test = AttendanceApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Attendance specific tests here
// <<< CUSTOM TESTS END >>>
