//! LeaveBalance API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the LeaveBalance CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// LEAVEBALANCE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for LeaveBalance
pub struct LeaveBalanceTestData;

impl TestDataGenerator for LeaveBalanceTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "leave_type_id": Uuid::new_v4().to_string(),
            "year": 1,
            "allocated": 0,
            "used": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "leave_type_id": Uuid::new_v4().to_string(),
            "year": 1,
            "allocated": 0,
            "used": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/employees", &super::employee_api_test::EmployeeTestData).await {
            deps.push(("employee_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/leave_types", &super::leave_type_api_test::LeaveTypeTestData).await {
            deps.push(("leave_type_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// LEAVEBALANCE API TEST
// ============================================================================

/// LeaveBalance API test suite
pub struct LeaveBalanceApiTest {
    inner: GenericCrudTest<LeaveBalanceTestData>,
}

impl LeaveBalanceApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/leave_balances", "LeaveBalance");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, LeaveBalanceTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for LeaveBalanceApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_leave_balance_crud() {
        let mut test = LeaveBalanceApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add LeaveBalance specific tests here
// <<< CUSTOM TESTS END >>>
