//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod attendance_api_test;
pub mod employee_api_test;
pub mod leave_application_api_test;
pub mod leave_balance_api_test;
pub mod leave_type_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use attendance_api_test::*;
pub use employee_api_test::*;
pub use leave_application_api_test::*;
pub use leave_balance_api_test::*;
pub use leave_type_api_test::*;
