//! Hr Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AttendanceService;
use crate::application::service::EmployeeService;
use crate::application::service::LeaveApplicationService;
use crate::application::service::LeaveBalanceService;
use crate::application::service::LeaveTypeService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Attendance service
    pub attendance_service: Arc<AttendanceService>,
    /// Employee service
    pub employee_service: Arc<EmployeeService>,
    /// LeaveApplication service
    pub leave_application_service: Arc<LeaveApplicationService>,
    /// LeaveBalance service
    pub leave_balance_service: Arc<LeaveBalanceService>,
    /// LeaveType service
    pub leave_type_service: Arc<LeaveTypeService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        attendance_service: Arc<AttendanceService>,
        employee_service: Arc<EmployeeService>,
        leave_application_service: Arc<LeaveApplicationService>,
        leave_balance_service: Arc<LeaveBalanceService>,
        leave_type_service: Arc<LeaveTypeService>
    ) -> Self {
        Self {
            attendance_service,
            employee_service,
            leave_application_service,
            leave_balance_service,
            leave_type_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::HrModule) -> Self {
        Self {
            attendance_service: module.attendance_service.clone(),
            employee_service: module.employee_service.clone(),
            leave_application_service: module.leave_application_service.clone(),
            leave_balance_service: module.leave_balance_service.clone(),
            leave_type_service: module.leave_type_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    attendance_service: Option<Arc<AttendanceService>>,
    employee_service: Option<Arc<EmployeeService>>,
    leave_application_service: Option<Arc<LeaveApplicationService>>,
    leave_balance_service: Option<Arc<LeaveBalanceService>>,
    leave_type_service: Option<Arc<LeaveTypeService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Attendance service.
    pub fn with_attendance_service(mut self, service: Arc<AttendanceService>) -> Self {
        self.attendance_service = Some(service);
        self
    }

    /// Set the Employee service.
    pub fn with_employee_service(mut self, service: Arc<EmployeeService>) -> Self {
        self.employee_service = Some(service);
        self
    }

    /// Set the LeaveApplication service.
    pub fn with_leave_application_service(mut self, service: Arc<LeaveApplicationService>) -> Self {
        self.leave_application_service = Some(service);
        self
    }

    /// Set the LeaveBalance service.
    pub fn with_leave_balance_service(mut self, service: Arc<LeaveBalanceService>) -> Self {
        self.leave_balance_service = Some(service);
        self
    }

    /// Set the LeaveType service.
    pub fn with_leave_type_service(mut self, service: Arc<LeaveTypeService>) -> Self {
        self.leave_type_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            attendance_service: self.attendance_service.expect("attendance_service is required"),
            employee_service: self.employee_service.expect("employee_service is required"),
            leave_application_service: self.leave_application_service.expect("leave_application_service is required"),
            leave_balance_service: self.leave_balance_service.expect("leave_balance_service is required"),
            leave_type_service: self.leave_type_service.expect("leave_type_service is required"),
        }
    }
}
