//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    attendance_handler::create_attendance_routes,
    employee_handler::create_employee_routes,
    leave_application_handler::create_leave_application_routes,
    leave_balance_handler::create_leave_balance_routes,
    leave_type_handler::create_leave_type_routes,
};

use crate::application::service::{
    AttendanceService,
    EmployeeService,
    LeaveApplicationService,
    LeaveBalanceService,
    LeaveTypeService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub attendance: Arc<AttendanceService>,
    pub employee: Arc<EmployeeService>,
    pub leave_application: Arc<LeaveApplicationService>,
    pub leave_balance: Arc<LeaveBalanceService>,
    pub leave_type: Arc<LeaveTypeService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Attendance routes (12 Backbone endpoints)
        .merge(create_attendance_routes(services.attendance))
        // Employee routes (12 Backbone endpoints)
        .merge(create_employee_routes(services.employee))
        // LeaveApplication routes (12 Backbone endpoints)
        .merge(create_leave_application_routes(services.leave_application))
        // LeaveBalance routes (12 Backbone endpoints)
        .merge(create_leave_balance_routes(services.leave_balance))
        // LeaveType routes (12 Backbone endpoints)
        .merge(create_leave_type_routes(services.leave_type))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn attendance_routes(service: Arc<AttendanceService>) -> Router {
        create_attendance_routes(service)
    }

    pub fn employee_routes(service: Arc<EmployeeService>) -> Router {
        create_employee_routes(service)
    }

    pub fn leave_application_routes(service: Arc<LeaveApplicationService>) -> Router {
        create_leave_application_routes(service)
    }

    pub fn leave_balance_routes(service: Arc<LeaveBalanceService>) -> Router {
        create_leave_balance_routes(service)
    }

    pub fn leave_type_routes(service: Arc<LeaveTypeService>) -> Router {
        create_leave_type_routes(service)
    }

}
