//! Public events for Hr module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ATTENDANCE EVENTS
// ============================================================================

/// Event published when a Attendance is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceCreatedEvent {
    pub id: AttendanceId,
    pub data: AttendanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Attendance is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceUpdatedEvent {
    pub id: AttendanceId,
    pub data: AttendanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Attendance is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceDeletedEvent {
    pub id: AttendanceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// EMPLOYEE EVENTS
// ============================================================================

/// Event published when a Employee is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCreatedEvent {
    pub id: EmployeeId,
    pub data: EmployeeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Employee is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeUpdatedEvent {
    pub id: EmployeeId,
    pub data: EmployeeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Employee is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeDeletedEvent {
    pub id: EmployeeId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// LEAVEAPPLICATION EVENTS
// ============================================================================

/// Event published when a LeaveApplication is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveApplicationCreatedEvent {
    pub id: LeaveApplicationId,
    pub data: LeaveApplicationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LeaveApplication is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveApplicationUpdatedEvent {
    pub id: LeaveApplicationId,
    pub data: LeaveApplicationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LeaveApplication is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveApplicationDeletedEvent {
    pub id: LeaveApplicationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// LEAVEBALANCE EVENTS
// ============================================================================

/// Event published when a LeaveBalance is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveBalanceCreatedEvent {
    pub id: LeaveBalanceId,
    pub data: LeaveBalanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LeaveBalance is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveBalanceUpdatedEvent {
    pub id: LeaveBalanceId,
    pub data: LeaveBalanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LeaveBalance is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveBalanceDeletedEvent {
    pub id: LeaveBalanceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// LEAVETYPE EVENTS
// ============================================================================

/// Event published when a LeaveType is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveTypeCreatedEvent {
    pub id: LeaveTypeId,
    pub data: LeaveTypeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LeaveType is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveTypeUpdatedEvent {
    pub id: LeaveTypeId,
    pub data: LeaveTypeDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a LeaveType is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveTypeDeletedEvent {
    pub id: LeaveTypeId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Hr module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum HrEvent {
    AttendanceCreated(AttendanceCreatedEvent),
    AttendanceUpdated(AttendanceUpdatedEvent),
    AttendanceDeleted(AttendanceDeletedEvent),
    EmployeeCreated(EmployeeCreatedEvent),
    EmployeeUpdated(EmployeeUpdatedEvent),
    EmployeeDeleted(EmployeeDeletedEvent),
    LeaveApplicationCreated(LeaveApplicationCreatedEvent),
    LeaveApplicationUpdated(LeaveApplicationUpdatedEvent),
    LeaveApplicationDeleted(LeaveApplicationDeletedEvent),
    LeaveBalanceCreated(LeaveBalanceCreatedEvent),
    LeaveBalanceUpdated(LeaveBalanceUpdatedEvent),
    LeaveBalanceDeleted(LeaveBalanceDeletedEvent),
    LeaveTypeCreated(LeaveTypeCreatedEvent),
    LeaveTypeUpdated(LeaveTypeUpdatedEvent),
    LeaveTypeDeleted(LeaveTypeDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HrEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for HrEventMetadata {
    fn default() -> Self {
        Self {
            module: "hr",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
