//! Hr Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Hr exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use hr::exports::{AttendanceDto, HrQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AttendanceDto` - Data transfer object for Attendance
/// - `AttendanceSummary` - Summary view of Attendance
/// - `AttendanceId` - Type-safe ID wrapper
/// - `EmployeeDto` - Data transfer object for Employee
/// - `EmployeeSummary` - Summary view of Employee
/// - `EmployeeId` - Type-safe ID wrapper
/// - `LeaveApplicationDto` - Data transfer object for LeaveApplication
/// - `LeaveApplicationSummary` - Summary view of LeaveApplication
/// - `LeaveApplicationId` - Type-safe ID wrapper
/// - `LeaveBalanceDto` - Data transfer object for LeaveBalance
/// - `LeaveBalanceSummary` - Summary view of LeaveBalance
/// - `LeaveBalanceId` - Type-safe ID wrapper
/// - `LeaveTypeDto` - Data transfer object for LeaveType
/// - `LeaveTypeSummary` - Summary view of LeaveType
/// - `LeaveTypeId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `HrQueryService` - Read-only queries
///
/// ## Public Events
/// - `AttendanceCreatedEvent` - Published when Attendance is created
/// - `AttendanceUpdatedEvent` - Published when Attendance is updated
/// - `AttendanceDeletedEvent` - Published when Attendance is deleted
/// - `EmployeeCreatedEvent` - Published when Employee is created
/// - `EmployeeUpdatedEvent` - Published when Employee is updated
/// - `EmployeeDeletedEvent` - Published when Employee is deleted
/// - `LeaveApplicationCreatedEvent` - Published when LeaveApplication is created
/// - `LeaveApplicationUpdatedEvent` - Published when LeaveApplication is updated
/// - `LeaveApplicationDeletedEvent` - Published when LeaveApplication is deleted
/// - `LeaveBalanceCreatedEvent` - Published when LeaveBalance is created
/// - `LeaveBalanceUpdatedEvent` - Published when LeaveBalance is updated
/// - `LeaveBalanceDeletedEvent` - Published when LeaveBalance is deleted
/// - `LeaveTypeCreatedEvent` - Published when LeaveType is created
/// - `LeaveTypeUpdatedEvent` - Published when LeaveType is updated
/// - `LeaveTypeDeletedEvent` - Published when LeaveType is deleted
pub struct ExportSummary;
