//! Public services for Hr module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Hr module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait HrQueryService: Send + Sync {
    /// Get Attendance by ID
    async fn get_attendance(&self, id: AttendanceId) -> Result<Option<AttendanceDto>>;

    /// Get Attendance summary by ID
    async fn get_attendance_summary(&self, id: AttendanceId) -> Result<Option<AttendanceSummary>>;

    /// Check if Attendance exists
    async fn attendance_exists(&self, id: AttendanceId) -> Result<bool>;

    /// Get Employee by ID
    async fn get_employee(&self, id: EmployeeId) -> Result<Option<EmployeeDto>>;

    /// Get Employee summary by ID
    async fn get_employee_summary(&self, id: EmployeeId) -> Result<Option<EmployeeSummary>>;

    /// Check if Employee exists
    async fn employee_exists(&self, id: EmployeeId) -> Result<bool>;

    /// Get LeaveApplication by ID
    async fn get_leave_application(&self, id: LeaveApplicationId) -> Result<Option<LeaveApplicationDto>>;

    /// Get LeaveApplication summary by ID
    async fn get_leave_application_summary(&self, id: LeaveApplicationId) -> Result<Option<LeaveApplicationSummary>>;

    /// Check if LeaveApplication exists
    async fn leave_application_exists(&self, id: LeaveApplicationId) -> Result<bool>;

    /// Get LeaveBalance by ID
    async fn get_leave_balance(&self, id: LeaveBalanceId) -> Result<Option<LeaveBalanceDto>>;

    /// Get LeaveBalance summary by ID
    async fn get_leave_balance_summary(&self, id: LeaveBalanceId) -> Result<Option<LeaveBalanceSummary>>;

    /// Check if LeaveBalance exists
    async fn leave_balance_exists(&self, id: LeaveBalanceId) -> Result<bool>;

    /// Get LeaveType by ID
    async fn get_leave_type(&self, id: LeaveTypeId) -> Result<Option<LeaveTypeDto>>;

    /// Get LeaveType summary by ID
    async fn get_leave_type_summary(&self, id: LeaveTypeId) -> Result<Option<LeaveTypeSummary>>;

    /// Check if LeaveType exists
    async fn leave_type_exists(&self, id: LeaveTypeId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
