//! Public types for Hr module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// ATTENDANCE TYPES
// ============================================================================

/// Type-safe ID for Attendance
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AttendanceId(pub Uuid);

impl AttendanceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AttendanceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AttendanceId> for Uuid {
    fn from(id: AttendanceId) -> Self {
        id.0
    }
}

/// Data transfer object for Attendance
///
/// This is the public representation of Attendance for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceDto {
    pub id: AttendanceId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub attendance_date: DateTime<Utc>,
    pub status: AttendanceStatus,
    pub working_hours: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of Attendance for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceSummary {
    pub id: AttendanceId,
    pub status: AttendanceStatus,
}

/// Reference to Attendance for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceRef {
    pub id: AttendanceId,
}

// ============================================================================
// EMPLOYEE TYPES
// ============================================================================

/// Type-safe ID for Employee
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeId(pub Uuid);

impl EmployeeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeId> for Uuid {
    fn from(id: EmployeeId) -> Self {
        id.0
    }
}

/// Data transfer object for Employee
///
/// This is the public representation of Employee for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeDto {
    pub id: EmployeeId,
    pub company_id: Uuid,
    pub employee_number: String,
    pub user_id: Option<Uuid>,
    pub department_id: Option<Uuid>,
    pub first_name: String,
    pub last_name: Option<String>,
    pub designation: Option<String>,
    pub employment_type: EmploymentType,
    pub date_of_joining: DateTime<Utc>,
    pub date_of_exit: Option<DateTime<Utc>>,
    pub status: EmployeeStatus,
    pub nik: Option<String>,
    pub npwp: Option<String>,
    pub tax_status: TaxStatus,
    pub bank_account_no: Option<String>,
    pub base_salary: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of Employee for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeSummary {
    pub id: EmployeeId,
    pub first_name: String,
    pub last_name: Option<String>,
    pub status: EmployeeStatus,
}

/// Reference to Employee for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeRef {
    pub id: EmployeeId,
}

// ============================================================================
// LEAVEAPPLICATION TYPES
// ============================================================================

/// Type-safe ID for LeaveApplication
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LeaveApplicationId(pub Uuid);

impl LeaveApplicationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for LeaveApplicationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<LeaveApplicationId> for Uuid {
    fn from(id: LeaveApplicationId) -> Self {
        id.0
    }
}

/// Data transfer object for LeaveApplication
///
/// This is the public representation of LeaveApplication for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveApplicationDto {
    pub id: LeaveApplicationId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub leave_type_id: Uuid,
    pub from_date: DateTime<Utc>,
    pub to_date: DateTime<Utc>,
    pub days: Decimal,
    pub status: LeaveStatus,
    pub reason: Option<String>,
    pub approved_by: Option<Uuid>,
    pub approved_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of LeaveApplication for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveApplicationSummary {
    pub id: LeaveApplicationId,
    pub status: LeaveStatus,
}

/// Reference to LeaveApplication for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveApplicationRef {
    pub id: LeaveApplicationId,
}

// ============================================================================
// LEAVEBALANCE TYPES
// ============================================================================

/// Type-safe ID for LeaveBalance
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LeaveBalanceId(pub Uuid);

impl LeaveBalanceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for LeaveBalanceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<LeaveBalanceId> for Uuid {
    fn from(id: LeaveBalanceId) -> Self {
        id.0
    }
}

/// Data transfer object for LeaveBalance
///
/// This is the public representation of LeaveBalance for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveBalanceDto {
    pub id: LeaveBalanceId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub leave_type_id: Uuid,
    pub year: i32,
    pub allocated: Decimal,
    pub used: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of LeaveBalance for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveBalanceSummary {
    pub id: LeaveBalanceId,
}

/// Reference to LeaveBalance for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveBalanceRef {
    pub id: LeaveBalanceId,
}

// ============================================================================
// LEAVETYPE TYPES
// ============================================================================

/// Type-safe ID for LeaveType
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LeaveTypeId(pub Uuid);

impl LeaveTypeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for LeaveTypeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<LeaveTypeId> for Uuid {
    fn from(id: LeaveTypeId) -> Self {
        id.0
    }
}

/// Data transfer object for LeaveType
///
/// This is the public representation of LeaveType for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveTypeDto {
    pub id: LeaveTypeId,
    pub company_id: Uuid,
    pub name: String,
    pub is_paid: bool,
    pub annual_quota_days: Decimal,
    pub allow_carry_forward: bool,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of LeaveType for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveTypeSummary {
    pub id: LeaveTypeId,
    pub name: String,
}

/// Reference to LeaveType for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeaveTypeRef {
    pub id: LeaveTypeId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
