//! Hr Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AttendanceService;
pub use application::service::EmployeeService;
pub use application::service::LeaveApplicationService;
pub use application::service::LeaveBalanceService;
pub use application::service::LeaveTypeService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Hr module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let hr = HrModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = hr.all_crud_routes();
/// ```
pub struct HrModule {
    pub attendance_service: Arc<AttendanceService>,
    pub employee_service: Arc<EmployeeService>,
    pub leave_application_service: Arc<LeaveApplicationService>,
    pub leave_balance_service: Arc<LeaveBalanceService>,
    pub leave_type_service: Arc<LeaveTypeService>,
}

impl HrModule {
    /// Create a new module builder
    pub fn builder() -> HrModuleBuilder {
        HrModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_attendance_routes,
            create_employee_routes,
            create_leave_application_routes,
            create_leave_balance_routes,
            create_leave_type_routes,
        };

        Router::new()
            .merge(create_attendance_routes(self.attendance_service.clone()))
            .merge(create_employee_routes(self.employee_service.clone()))
            .merge(create_leave_application_routes(self.leave_application_service.clone()))
            .merge(create_leave_balance_routes(self.leave_balance_service.clone()))
            .merge(create_leave_type_routes(self.leave_type_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for HrModule
pub struct HrModuleBuilder {
    db_pool: Option<PgPool>,
}

impl HrModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<HrModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Attendance service
        let attendance_repository = Arc::new(AttendanceRepository::new(db_pool.clone()));
        let attendance_service = Arc::new(AttendanceService::with_repository(attendance_repository.clone()));

        // Employee service
        let employee_repository = Arc::new(EmployeeRepository::new(db_pool.clone()));
        let employee_service = Arc::new(EmployeeService::with_repository(employee_repository.clone()));

        // LeaveApplication service
        let leave_application_repository = Arc::new(LeaveApplicationRepository::new(db_pool.clone()));
        let leave_application_service = Arc::new(LeaveApplicationService::with_repository(leave_application_repository.clone()));

        // LeaveBalance service
        let leave_balance_repository = Arc::new(LeaveBalanceRepository::new(db_pool.clone()));
        let leave_balance_service = Arc::new(LeaveBalanceService::with_repository(leave_balance_repository.clone()));

        // LeaveType service
        let leave_type_repository = Arc::new(LeaveTypeRepository::new(db_pool.clone()));
        let leave_type_service = Arc::new(LeaveTypeService::with_repository(leave_type_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(HrModule {
            attendance_service,
            employee_service,
            leave_application_service,
            leave_balance_service,
            leave_type_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for HrModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
