//! Use case type aliases for Attendance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAttendanceDto, UpdateAttendanceDto};
use crate::application::service::AttendanceService;
use crate::domain::entity::Attendance;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAttendanceUseCase = CreateUseCase<Attendance, CreateAttendanceDto, AttendanceService>;
pub type UpdateAttendanceUseCase = UpdateUseCase<Attendance, UpdateAttendanceDto, AttendanceService>;
pub type GetAttendanceUseCase    = GetUseCase<Attendance, AttendanceService>;
pub type DeleteAttendanceUseCase = DeleteUseCase<Attendance, AttendanceService>;
pub type ListAttendanceUseCase   = ListUseCase<Attendance, AttendanceService>;

// <<< CUSTOM
// END CUSTOM
