//! Use case type aliases for Employee aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmployeeDto, UpdateEmployeeDto};
use crate::application::service::EmployeeService;
use crate::domain::entity::Employee;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmployeeUseCase = CreateUseCase<Employee, CreateEmployeeDto, EmployeeService>;
pub type UpdateEmployeeUseCase = UpdateUseCase<Employee, UpdateEmployeeDto, EmployeeService>;
pub type GetEmployeeUseCase    = GetUseCase<Employee, EmployeeService>;
pub type DeleteEmployeeUseCase = DeleteUseCase<Employee, EmployeeService>;
pub type ListEmployeeUseCase   = ListUseCase<Employee, EmployeeService>;

// <<< CUSTOM
// END CUSTOM
