//! Use case type aliases for LeaveType aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateLeaveTypeDto, UpdateLeaveTypeDto};
use crate::application::service::LeaveTypeService;
use crate::domain::entity::LeaveType;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateLeaveTypeUseCase = CreateUseCase<LeaveType, CreateLeaveTypeDto, LeaveTypeService>;
pub type UpdateLeaveTypeUseCase = UpdateUseCase<LeaveType, UpdateLeaveTypeDto, LeaveTypeService>;
pub type GetLeaveTypeUseCase    = GetUseCase<LeaveType, LeaveTypeService>;
pub type DeleteLeaveTypeUseCase = DeleteUseCase<LeaveType, LeaveTypeService>;
pub type ListLeaveTypeUseCase   = ListUseCase<LeaveType, LeaveTypeService>;

// <<< CUSTOM
// END CUSTOM
