//! Use case type aliases for LeaveBalance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateLeaveBalanceDto, UpdateLeaveBalanceDto};
use crate::application::service::LeaveBalanceService;
use crate::domain::entity::LeaveBalance;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateLeaveBalanceUseCase = CreateUseCase<LeaveBalance, CreateLeaveBalanceDto, LeaveBalanceService>;
pub type UpdateLeaveBalanceUseCase = UpdateUseCase<LeaveBalance, UpdateLeaveBalanceDto, LeaveBalanceService>;
pub type GetLeaveBalanceUseCase    = GetUseCase<LeaveBalance, LeaveBalanceService>;
pub type DeleteLeaveBalanceUseCase = DeleteUseCase<LeaveBalance, LeaveBalanceService>;
pub type ListLeaveBalanceUseCase   = ListUseCase<LeaveBalance, LeaveBalanceService>;

// <<< CUSTOM
// END CUSTOM
