//! Use case type aliases for LeaveApplication aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateLeaveApplicationDto, UpdateLeaveApplicationDto};
use crate::application::service::LeaveApplicationService;
use crate::domain::entity::LeaveApplication;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateLeaveApplicationUseCase = CreateUseCase<LeaveApplication, CreateLeaveApplicationDto, LeaveApplicationService>;
pub type UpdateLeaveApplicationUseCase = UpdateUseCase<LeaveApplication, UpdateLeaveApplicationDto, LeaveApplicationService>;
pub type GetLeaveApplicationUseCase    = GetUseCase<LeaveApplication, LeaveApplicationService>;
pub type DeleteLeaveApplicationUseCase = DeleteUseCase<LeaveApplication, LeaveApplicationService>;
pub type ListLeaveApplicationUseCase   = ListUseCase<LeaveApplication, LeaveApplicationService>;

// <<< CUSTOM
// END CUSTOM
