//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod attendance_usecases;
pub mod employee_usecases;
pub mod leave_application_usecases;
pub mod leave_balance_usecases;
pub mod leave_type_usecases;

pub use attendance_usecases::{
    CreateAttendanceUseCase, UpdateAttendanceUseCase, GetAttendanceUseCase,
    DeleteAttendanceUseCase, ListAttendanceUseCase,
};
pub use employee_usecases::{
    CreateEmployeeUseCase, UpdateEmployeeUseCase, GetEmployeeUseCase,
    DeleteEmployeeUseCase, ListEmployeeUseCase,
};
pub use leave_application_usecases::{
    CreateLeaveApplicationUseCase, UpdateLeaveApplicationUseCase, GetLeaveApplicationUseCase,
    DeleteLeaveApplicationUseCase, ListLeaveApplicationUseCase,
};
pub use leave_balance_usecases::{
    CreateLeaveBalanceUseCase, UpdateLeaveBalanceUseCase, GetLeaveBalanceUseCase,
    DeleteLeaveBalanceUseCase, ListLeaveBalanceUseCase,
};
pub use leave_type_usecases::{
    CreateLeaveTypeUseCase, UpdateLeaveTypeUseCase, GetLeaveTypeUseCase,
    DeleteLeaveTypeUseCase, ListLeaveTypeUseCase,
};

// <<< CUSTOM
// END CUSTOM
