//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod attendance_handler;
pub mod employee_handler;
pub mod leave_application_handler;
pub mod leave_balance_handler;
pub mod leave_type_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use attendance_handler::{create_attendance_routes, create_attendance_read_routes, create_attendance_write_routes};
pub use employee_handler::{create_employee_routes, create_employee_read_routes, create_employee_write_routes};
pub use leave_application_handler::{create_leave_application_routes, create_leave_application_read_routes, create_leave_application_write_routes};
pub use leave_balance_handler::{create_leave_balance_routes, create_leave_balance_read_routes, create_leave_balance_write_routes};
pub use leave_type_handler::{create_leave_type_routes, create_leave_type_read_routes, create_leave_type_write_routes};
// <<< CUSTOM
// END CUSTOM
